### ISSUE TITLE
Error Serialization truncates text

### ISSUE THREAD

**Issue by guenthi** [ical-org/ical.net#109]
In DDCal serialization works as exepcted - in Ical.Net the content of the ics file is truncated

Code used for serialization:
CalendarSerializer ser = new CalendarSerializer();
ser.Serialize(cal, outFile);             

the end of file is truncated

missing content:
...nde 11
UID:8e7232f1-e563-48ec-af14-d87b6f526c5d
END:VEVENT
END:VCALENDAR

**Comment by rianjs** [comment]
Do you still get unexpected output when you follow the directions here?

https://github.com/rianjs/ical.net/wiki

`serializer.Serialize()` is not the method call you should use.

**Comment by guenthi** [comment]
this path is working
I appreciate your support and your work
br Guenther

**Comment by rianjs** [comment]
Glad to hear it!

(I've made the same mistake, too. `.Serialize()` seems a more natural thing to call than `.SerializeToString()`. Perhaps I should look at making that method `internal`.)
