### ISSUE TITLE
Possible to change namespace Utility?

### ISSUE THREAD

**Issue by mcain66** [ical-org/ical.net#116]
CollectionHelpers.cs establishes namespace Utility.  This conflicts with my own project's use of Utility and requires using extern alias - which must be manually updated each time there is an update to ical.net.  Would it be possible to eliminate namespace Utility within iCal and move GetHashCode() to another location, perhaps Ical.Net.Utility?

**Comment by rianjs** [comment]
Yeah, the namespaces are a mess. My fear is that going through and really organizing them will be severely breaking change(s) to consumers of the library, and I feel like revving the major version a million times isn't the best plan ever.

In this case, I've changed the root namespace to be Ical.Net by default, which it should have been all along. I've also moved the Utility namespace to Ical.Net.Utility.

nuget version 2.2.11 contains the change.

5bfe9a752783b1063a0698c0d3895781ec0ecb75
