### ISSUE TITLE
Xamarin Package?

### ISSUE THREAD

**Issue by wmansfield** [ical-org/ical.net#127]
Can you guys make a Xamarin build? Given that, full stack calendar solutions become cake.

**Comment by rianjs** [comment]
Possibly ignorant questions:
- I assume you mean a mono build?
- Would  a .NET Core build mean you don't need a Xamarin build?

I'm not familiar with mono or the Xamarin ecosystem. I also don't know what it's future is, given the existence of .NET Core.

**Comment by rianjs** [comment]
Reading [this thread](https://www.reddit.com/r/csharp/comments/1u9bku/any_way_to_target_mono_in_vs2012/), it seems that mono can use already-compiled assemblies, provided they don't make use of anything Windows-specific. I got rid of most of the really platform-specific stuff when I was working on the .NET Core port.

Have you tried just using the .NET 4.0 DLLs in the nuget package to see if they work under mono?

**Comment by wmansfield** [comment]
I will give the 4.0 assemblies a shot on Monday. If they work, then it should just be a simple chore to get the proper nuget targeting set up.  Xamarin can import .NET Standard, but I am rather sure .NET Core is out of the mix. [at least directly, but compiling the same code with a different target will likely work fine]. I'll let ya know. If I get it working, then my app will gain calendar recurrence. If not, it won't. :)

**Comment by rianjs** [comment]
If something barfs with the 4.0 DLLs, and you have a useful stack trace, let me know. Chances are it's a localization thing, and may be easy to work around. (That's how a lot of the .NET Core breakages were.)

**Comment by rianjs** [comment]
If using the 4.0 binaries doesn't work, just re-open this with any new information you can provide. (Just doing some housekeeping.)
