### ISSUE TITLE
Auto-generate documentation, and host it somewhere

### ISSUE THREAD

**Issue by doug62** [ical-org/ical.net#139]
First off - Thanks for doing this.  I'm wondering where the class/function/API documentation went? A copy of the old would be close enough?

**Comment by rianjs** [comment]
It's in the back of my mind, but I don't have a ticket for it (until now! huzzah!). I would like to:
- Register a domain icaldotnet.net (ha!) or something
- Have [NodaTime-like](http://nodatime.org/1.3.x/api/) API documentation

I looked into it a little while ago, and there didn't seem to be any obvious winners in the turn-my-XML-into-reasonable-docs department, but Sandcastle(?) seemed to be the most powerful.

I have a VPS that I can host another domain on, no problem. The main thing is tooling: I'm not familiar with the XML documentation generators.

**Comment by cboseak** [comment]
GhostDoc is another solution, it generates MSDN style documentation and allows you give code examples. I believe you have the option to output as html. 

I'll volunteer hosting if you do not already have it.

Edit: just looked at the nodetime documentation..... ghost doc is similar to this.

**Comment by Nixill** [comment]
Any progress on this?
