### ISSUE TITLE
GetOccurrences returns wrong the first occurrence 

### ISSUE THREAD

**Issue by gilmishal** [ical-org/ical.net#142]
I am using Ical.net version 2.2.13 and there is a bug, that I can reproduce everytime. 

When I use Event GetOccurences, for my icalendar definition, I am getting The first occurence of the VEvent, even when it isn't in the range.

This is the code that reproduces the bug

``` cs
IEvent vEvent;
using (var strm = new MemoryStream(Encoding.UTF8.GetBytes("BEGIN:VEVENT\nSUMMARY:Abraham Lincoln\nRRULE:FREQ=DAILY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR\nDTSTART:20160901T083000Z\nDTEND:20170701\nEND:VEVENT")))           
{
    EventSerializer serializer = new EventSerializer();
    vEvent = (IEvent)serializer.Deserialize(strm, Encoding.UTF8);
}
var cal = new Calendar();
cal.Events.Add(vEvent);
cal.AddTimeZone(new VTimeZone("UTC"));
HashSet<Occurrence> occurrences = cal.GetOccurrences(startTime, endTime);
```

when I put startTime as September 19 - I get an occurence at September 1st, and that shouldn't be. Other than that, the rest of the occurences are correct.

**Comment by posics** [comment]
did you try vEvent.getOccurrences(startTime, endTime) rather than cal.getOccurrences(startTime, endTime)?

**Comment by AVee** [comment]
~~I've got a similar issue, but I'm using RecurrenceUtil.GetOccurrences(). Changing that code to vEvent.getOccurrences() also returns incorrect results, but those are wrong in a different way. 
I'll try to come up with a test case later.~~

I looks like it's a different scenario, so I've created a new issue (#175)

**Comment by streviranus** [comment]
I have a similar issue of the DtStart date not matching the RRULE and have figured out a work around using the RecurrencePatternEvaluator.
```
// 3/1/2017 is a wednesday so it shouldn't display in the occurrences
var vEvent = new Event {
 DtStart = new CalDateTime(newDateTime(2017, 3, 1, 9, 0, 0)),
 DtEnd = new CalDateTime(newDateTime(2017, 3, 1, 10, 0, 0))
};
var recurrenceRule = new RecurrencePattern(FrequencyDayType.Weekly, 1) {
 ByDay = new IList<IWeekday> { new WeekDay(DayOfWeek.Thursday) }
};
var recurrenceEvaluator = new RecurrencePatternEvaluator(recurrenceRule);
var searchStart = new DateTime(2017, 3, 1, 0, 0, 0);
var searchEnd = new DateTime(2017, 3, 17, 0, 0, 0);
var correctOccurrences = recurrenceEvaluator.Evaluate(vEvent.DtStart, searchStart, searchEnd, false);
```
Occurrence should equal 3/2/2017, 3/9/2017, and 3/16/2017. By setting the parameter includeReferenceDateInResults to false only adds the DtStart to the occurrences if it matches the RRULE.

**Comment by eduardotolino** [comment]
same problem. 
any solution by the library? 
or just through workaround?

**Comment by ajaynarvekar** [comment]
> I have a similar issue of the DtStart date not matching the RRULE and have figured out a work around using the RecurrencePatternEvaluator.
> 
> ```
> // 3/1/2017 is a wednesday so it shouldn't display in the occurrences
> var vEvent = new Event {
>  DtStart = new CalDateTime(newDateTime(2017, 3, 1, 9, 0, 0)),
>  DtEnd = new CalDateTime(newDateTime(2017, 3, 1, 10, 0, 0))
> };
> var recurrenceRule = new RecurrencePattern(FrequencyDayType.Weekly, 1) {
>  ByDay = new IList<IWeekday> { new WeekDay(DayOfWeek.Thursday) }
> };
> var recurrenceEvaluator = new RecurrencePatternEvaluator(recurrenceRule);
> var searchStart = new DateTime(2017, 3, 1, 0, 0, 0);
> var searchStart = new DateTime(2017, 3, 17, 0, 0, 0);
> var correctOccurrences = recurrenceEvaluator.Evaluate(vEvent.DtStart, searchStart, searchEnd, false);
> ```
> 
> Occurrence should equal 3/2/2017, 3/9/2017, and 3/16/2017. By setting the parameter includeReferenceDateInResults to false only adds the DtStart to the occurrences if it matches the RRULE.

You're resetting the value of searchStart to 17th March, instead of setting searchEnd to it. Anyways, any solution so far?

**Comment by kosmonavtsv** [comment]
It can be due to broken `RecurrencePatternEvaluator`. It returns first wrong occurrence in some cases.
```csharp
var evaluator = new RecurrencePatternEvaluator(new RecurrencePattern(FrequencyType.Weekly, 2)
{
	ByDay = new List<WeekDay> { new WeekDay { DayOfWeek = DayOfWeek.Monday } }
});

var recurringPeriods = evaluator.Evaluate(
	referenceDate: new CalDateTime(DateTime.Parse("11/01/2021 8:00:00 AM", CultureInfo.InvariantCulture)),
	periodStart: DateTime.Parse("12/01/2021 8:00:00 AM", CultureInfo.InvariantCulture),
	periodEnd: DateTime.Parse("12/30/2021 8:00:00 AM", CultureInfo.InvariantCulture),
	includeReferenceDateInResults: false);

var firstOcurrence = recurringPeriods.First();
// Here we have firstOcurrence.StartTime = '11/29/2021 8:00:00 AM'
```

**Comment by nykez** [comment]
This is still happening as of version: 4.2.0 of Ical.NET.

Calendar.GetOccurences() returns the first occurence in the vEvent even if it is not in the scope of the fromStart, fromEnd paramters.
