### ISSUE TITLE
V2.3.1 Broke .Net 4.0 Compatability

### ISSUE THREAD

**Issue by SonarBeserk** [ical-org/ical.net#145]
When I tried to use nuget to install the package in a project targeting 4.0 the installation fails. Nuget spits out an error message about the package containing no 4.0 files. However if you rollback to v2.2.14 there is no issue installing.

**Comment by rianjs** [comment]
Thanks, I'll see about marking 2.3.\* as experimental for now -- it's a PCL version that should (I think) work with all the Xamarin stuff and maybe .NET Core. But breaking .NET 4 is bad, so I'll mark it experimental.

Other than that, it doesn't have anything that 2.2.14 does not.

**Comment by rianjs** [comment]
I've unpublished 2.3.1 and published it as a prerelease instead:

https://www.nuget.org/packages/Ical.Net

**Comment by rianjs** [comment]
I think what I'm going to do is create a new "branch" for v3 that will live side-by-side with the v2 code. v3 will target [netstandard 1.1](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms), which is what most .NET developers would think of as ".NET 4.5" -- it includes async-await, etc. IOW, it's the 4.5 API surface area.

v2 will continue to get bugfixes, but I think it will become the "legacy" version that can be used from .NET 4. I've already started doing this, I just forgot to mention it here.
