### ISSUE TITLE
Event.Copy should do a deep copy

### ISSUE THREAD

**Issue by posics** [ical-org/ical.net#149]
If I do
var tmpEvent = permanentEvent.Copy<IEvent>();
var newStart = new CalDateTime(blabla);
tmpEvent.Start = newStart;

then permanentEvent.Start has also changed to newStart. Shouldn't IEvent.Copy<T>() do a deep copy and return a new instance with all things copied over, not just references?

I am doing all this because permanentEvent.getOccurrences(startTime, endTime) is returning occurences with just the start time set correctly and duration 0 (I see no end time anyway) and I need to calculate  end and duration for each occurrence manually by creating a new event and copying stuff from permanentEvent. If getOccurrences() worked fine then I wouldn't have spotted this oddity.
Or maybe it's the lack of documentation that is confusing me. Can we have that documentation please?

**Comment by rianjs** [comment]
Yep, sounds like a bug. I may have introduced it when I was evaluating all the usages of `Copy` in ical a few months ago. (Or maybe I didn't, and it's always been there.)

**Comment by KotM** [comment]
Hi @rianjs ,

could you please explain why this bug was closed? I tried to do an event copy (want to create an Exception from a recurrent event), but this is not actual copy, because changing the event field (e.g. Summary) also changes the parent fields value as well.

            var parentEvent = new Event();
            parentEvent.Start = new CalDateTime(2015, 1, 1);
            parentEvent.Summary = "parent summary";

            var copy = parentEvent.Copy<Event>();

            copy.Start = new CalDateTime(2016, 1, 1);
            copy.Summary = "not parent summary";

            Assert.AreNotEqual(parentEvent.Start, copy.Start); // fails!
            Assert.AreNotEqual(parentEvent.Summary, copy.Summary); // fails!

I have no other possibility to create copy of new event except serialize/deserialize, but it is poor performance.

**Comment by rianjs** [comment]
It isn’t closed.

**Comment by KotM** [comment]
Sorry for misunderstanding, very latest "Duplicate property DESCRIPTION" at the end of the list has confused me a bit. :)

So, do you have any plans and estimations for fixing this issue? 

Or maybe you can propose another workaround except mentioned above serialize/deserialize approach?

Thank you in advance.

**Comment by rianjs** [comment]
> So, do you have any plans and estimations for fixing this issue?

No.

> Or maybe you can propose another workaround except mentioned above serialize/deserialize approach?

That's what we do today, hundreds of `VCALENDAR`s and `VEVENT`s at a time, often as part of a click handler because it's fast enough, especially if you're working with collections `AsParallel()`.

**Comment by axunonb** [comment]
Looks like `Event` has been renamed and it's now about `CalendarEvent`:
```C#
[Test]
public void DeepCopy()
{
    var parentEvent = new CalendarEvent
    {
        Start = new CalDateTime(2015, 1, 1),
        Summary = "parent summary"
    };

    var copy = parentEvent.Copy<CalendarEvent>();

    copy.Start = new CalDateTime(2016, 1, 1);
    copy.Summary = "not parent summary";

    Assert.Multiple(() =>
    {
        Assert.That(parentEvent.Start, Is.Not.EqualTo(copy.Start)); // fails!
        Assert.That(parentEvent.Summary, Is.Not.EqualTo(copy.Summary)); // fails!
    });
}
```

**Comment by axunonb** [comment]
@minichma 
This change would resolve the issue. Too simple to be true?

Current:
https://github.com/ical-org/ical.net/blob/00fd8c3c3508c097f928a8285cb94dde247db901/Ical.Net/CalendarComponents/CalendarComponent.cs#L51-L54

Change to:
```C#
foreach (var p in c.Properties)
{
    // Returns a deep copy of the current object
    // Uses CalendarObjectBase.Copy<T>()
    Properties.Add(p.Copy<ICalendarProperty>());
}
```

**Comment by minichma** [comment]
Good to see, the old ones is being worked on :-) It's still not deep in all branches I think. E.g. the following still fails:

```cs
        [Test]
        public void DeepCopy()
        {
            var parentEvent = new CalendarEvent
            {
                Start = new CalDateTime(2015, 1, 1),
                Summary = "parent summary"
            };

            var copy = parentEvent.Copy<CalendarEvent>();

            copy.Start.Value = new DateTime(2016, 2, 3);
            copy.Summary = "not parent summary";

            Assert.Multiple(() =>
            {
                Assert.That(parentEvent.Start, Is.Not.EqualTo(copy.Start)); // fails!
                Assert.That(parentEvent.Summary, Is.Not.EqualTo(copy.Summary)); // fails!
            });
        }
```

In a quick research I identified the following that probably should also be handled:

https://github.com/ical-org/ical.net/blob/00fd8c3c3508c097f928a8285cb94dde247db901/Ical.Net/CalendarObject.cs#L82

=> `this.AddChild(child.Copy<ICalendarObject>());`

and

https://github.com/ical-org/ical.net/blob/00fd8c3c3508c097f928a8285cb94dde247db901/Ical.Net/CalendarProperty.cs#L74

=> `SetValue(p.Values?.Select(x => (x as ICopyable)?.Copy<object>() ?? x).ToList());`

But I'm not sure which other effects this would have. Is this a breaking change? Probably yes. Do we have to deal with potential loops (an object referencing itself in any way)?

**Comment by axunonb** [comment]
Yep, I came across the same issues. `List`s are not deep copied in general, and self-referencing would crash.
I keep working on that.
