### ISSUE TITLE
UIDs should be *optionally* auto-generated.

### ISSUE THREAD

**Issue by rianjs** [ical-org/ical.net#15]
While there, make sure that they're only implemented for VEVENT, VTODO, VJOURNAL, and VFREEBUSY blocks, per the spec:

http://www.kanzaki.com/docs/ical/uid.html

**Comment by brianhy** [comment]
@rianjs, if I were to work on this would we be able to get it into the ical.net project within a week of submitting the PR?  We've got a business need driving the need for Uid to be optional (even including VEVENT, VTODO, etc.).  I've noticed there are many PRs open, but I'm hoping this project is still being supported.
