### ISSUE TITLE
Failing unit tests when run from mono/linux (on master)

### ISSUE THREAD

**Issue by fvn-linagora** [ical-org/ical.net#152]
most failing tests are using Calendar.LoadFromStream() with local datetimes.

see attached files for errors detail.

[TestResult.xml.txt](https://github.com/rianjs/ical.net/files/506192/TestResult.xml.txt)
[ical.failures.txt](https://github.com/rianjs/ical.net/files/506190/ical.failures.txt)

**Comment by rianjs** [comment]
Should be fixed in non-beta versions of 3+
