### ISSUE TITLE
Strong named assemblies

### ISSUE THREAD

**Issue by vijaydeep** [ical-org/ical.net#159]
I am working with SharePoint and my project dll is deployed to GAC. And this requires all the dependencies, including Ical.Net.dll and Ical.net.collections.dll to be strongly named. Do you have strong named assemblies that I can use. 

I am using the Ical.net Nuget package version 2.3.1.

**Comment by rianjs** [comment]
I do not have a strong named version, no. It IS a reasonable feature, though.

**Comment by fvn-linagora** [comment]
There have been previous [discussions](https://github.com/miensol/SimpleConfigSections/issues/3#issuecomment-219826659) for similar strong naming requests in other OSS projects
[dsplaisted/strongnamer](https://github.com/dsplaisted/strongnamer) is one way to deal with this.

**Comment by dolunay** [comment]
You must create a key.snk file from "Project Properties"->"Signing" page. check "Sign The Assembly" box and set password. Save the project and build it.

**Comment by josteink** [comment]
@rianjs This is *really easy* to implement. If someone submitted a PR for this, would you be willing to publish this new, strong-named version?

**Comment by rianjs** [comment]
https://www.nuget.org/packages/Ical.Net/2.3.6

**Comment by rianjs** [comment]
https://www.nuget.org/packages/Ical.Net/4.1.10

**Comment by josteink** [comment]
That's absolutely great and I'm sure will be appreciated.

Many thanks!
