### ISSUE TITLE
Inconsistent namespaces: "ical.NET" <-> "Ical.Net"

### ISSUE THREAD

**Issue by markuspalme** [ical-org/ical.net#160]
Namespaces are inconsistent, a few classes live in `ical.NET`, most in `Ical.Net`. This leads to a confusing intellisense experience:

![ns](https://cloud.githubusercontent.com/assets/1481801/19471540/f726d6c4-9523-11e6-9f36-3aadef7437b3.PNG)

**Comment by markuspalme** [comment]
Aligning the namespaces would be a breaking change. Would a PR be welcome anyway?

**Comment by rianjs** [comment]
I've already aligned the cases in my `v3` branch as `ical.net.namespace`. I will probably use the Framework Design Guidelines and have it be `Ical.Net.Namespace` before publishing v3.

**Comment by markuspalme** [comment]
Cool, I didn't see that branch. Thanks for the quick update.
