### ISSUE TITLE
Get ocurrences by recurrence rule and start, end date

### ISSUE THREAD

**Issue by ghost** [ical-org/ical.net#177]
I need with a recurrence rule and start, end date 
get all ocurrences, it is because i need to save a different record 
in the database with their own dates 

Thanks

**Comment by rianjs** [comment]
You'll have to be a little more specific about what you're trying to accomplish.

When you use `GetOccurrences`, you specify search start and end dates. If you want to search for a large chunk of time, just search for 100 years ago as the start, and 100 years in the future as the end.

If I have misunderstood your question, please re-open this ticket with a code sample and/or ical text that explains what you mean.

**Comment by ghost** [comment]
Hello,  thanks you for your response @rianjs 

Ok, I use kendo scheduler, when the user select for a recurrence, kendo provide me a recurrence rule string and kendo approach is save one receord with this rule,

I need to convert the recurrence rule, with the start and end of the event to all specific dates with the rule, to save one record by ocurrence

Example.

var start= new DateTime();
var end = new DateTime();
var rule = "FREQ=WEEKLY;BYDAY=WE;INTERVAL=1";

 DDay.iCal.RecurrencePattern rr = new DDay.iCal.RecurrencePattern(rule );

```
DDay.iCal.IEvent evt = new DDay.iCal.Event();
evt.RecurrenceRules.Add(rr);
evt.Start = new DDay.iCal.iCalDateTime(start);
evt.End= new DDay.iCal.iCalDateTime(end );
```

I need anything like : 
foreach(var sigleEvent in evt.GetAllDates())
{
      // Here i need specific start, end of each ocurrence in the rule.
}

Thanks you so much.
Regards.
David
