### ISSUE TITLE
GetOccurrences(startDate, endDate) does not return last occurrence if the recurrent event has ends on date

### ISSUE THREAD

**Issue by manojmore** [ical-org/ical.net#193]
Using Ical.net version 2.1.0.14533

I am trying to fetch events from google calendar.
It has recurrent Event which has ends on date(31 Dec 2016).
When I try to get the occurrences of this events it does not fetch the last occurrence ie. the occurrence of 31st December 2016.

**It works fine if the recurring event is an All Day Event.**

![image](https://cloud.githubusercontent.com/assets/5063843/20796969/d5e380b8-b7fe-11e6-963a-6e8c71e48e5d.png)

**Comment by rianjs** [comment]
The latest version of ical.net is 2.2.20. Please update to the latest version and see if that solves your problem.

If it doesn't, feel free to to re-open, but I did a lot of work on GetOccurrences, and added many more unit tests in that area.

**Comment by manojmore** [comment]
Thank you Rianjs for such a prompt response.

Tried with 2.2.20 and 2.3.1-xamarin-alpha versions but no luck , issue is still reproducible.

**Comment by manojmore** [comment]
Could you open this issue? #193

**Comment by rianjs** [comment]
Can you give me the ICS text behind the calendar event?

**Comment by manojmore** [comment]
[basic.txt](https://github.com/rianjs/ical.net/files/636233/basic.txt)
Attached is the ICS text for the calendar.  

**Getting the issue if the recurring event is an not All Day Event.**

**Comment by manojmore** [comment]
Any updates on this issue? as it is reproducible for below ICS;

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Manoj Calendar
X-WR-TIMEZONE:Asia/Calcutta
X-WR-CALDESC:Manoj Calendar
BEGIN:VTIMEZONE
TZID:Asia/Calcutta
X-LIC-LOCATION:Asia/Calcutta
BEGIN:STANDARD
TZOFFSETFROM:+0530
TZOFFSETTO:+0530
TZNAME:+0530
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Asia/Calcutta:20161201T100000
DTEND;TZID=Asia/Calcutta:20161201T110000
RRULE:FREQ=DAILY;UNTIL=20161231T043000Z
DTSTAMP:20161207T094319Z
UID:gd5h467cd73mc9qm1br69pr5vk@google.com
CREATED:20161205T072943Z
DESCRIPTION:
LAST-MODIFIED:20161207T093957Z
LOCATION:
SEQUENCE:3
STATUS:CONFIRMED
SUMMARY:Ends ON
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
DTSTART:20161004T043000Z
DTEND:20161004T053000Z
DTSTAMP:20161207T094319Z
UID:tdtep9c4sm9honrdrlodnd58fk@google.com
CREATED:20161004T135909Z
DESCRIPTION:Non Recurring Event
LAST-MODIFIED:20161014T092328Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Non Recurring Event
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20161004
DTEND;VALUE=DATE:20161005
DTSTAMP:20161207T094319Z
UID:onb0qubhjo8jsdrp2nl0i5aih8@google.com
CREATED:20161004T135708Z
DESCRIPTION:
LAST-MODIFIED:20161006T132320Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:All Day SIngle
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20161004
DTEND;VALUE=DATE:20161007
DTSTAMP:20161207T094319Z
UID:l2e0i0c3ik9q9phcefn4q1us78@google.com
CREATED:20161004T135655Z
DESCRIPTION:
LAST-MODIFIED:20161006T132252Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:All Day Event for 3 days
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Calcutta:20161004T060000
DTEND;TZID=Asia/Calcutta:20161004T070000
RRULE:FREQ=DAILY;UNTIL=20161006T182959Z
EXDATE;TZID=Asia/Calcutta:20161006T060000
EXDATE;TZID=Asia/Calcutta:20161005T060000
EXDATE;TZID=Asia/Calcutta:20161004T060000
DTSTAMP:20161207T094319Z
UID:ev6v6amrpgjdkgvhst5f4h05h0@google.com
CREATED:20161006T090909Z
DESCRIPTION:
LAST-MODIFIED:20161006T091011Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Daily Recurrence - Ends on
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
