### ISSUE TITLE
GetOccurences seems to mangle the event list

### ISSUE THREAD

**Issue by maxmanzero** [ical-org/ical.net#195]
I am pulling a calendar from a client's google calendar and running it through Ical.Net.

However, when I look at the events list in my database it seems as though a lot of the events have been lost or overwritten by recurring events. This seems to happen when we call GetOccurences.

**Comment by rianjs** [comment]
Please provide the ICS text that you're parsing, and a description of what you see vs what you expected to see.

**Comment by maxmanzero** [comment]
I have attached the ICS and 2 screen shots. One is of the ICS after it has been imported into Outlook and the other is after it has gone through our saving process. The Outlook image is what we are looking for based on what the client wants to see.

I should also mention that I am compiling the V2 source myself to add strong naming to the assemblies.

The call below is what we are doing in C#
stDate is defined as 2 months into the past from today
endDate is defined as 12 months into the future from today
iCalList = iCalfeed.GetOccurrences(stDate, endDate);

![outlookimport](https://cloud.githubusercontent.com/assets/3235976/20930725/946c5942-bb9c-11e6-9636-c48bdb7a6a1c.png)
![calendarimport](https://cloud.githubusercontent.com/assets/3235976/20930724/946ac636-bb9c-11e6-97f9-652fcc681ff3.png)
[basic.zip](https://github.com/rianjs/ical.net/files/633838/basic.zip)

Thanks for your help!

**Comment by rianjs** [comment]
Your ICS file is nearly 17,000 lines long. It's impossible for me (or any other human) to get anything useful out of it. If you could narrow down what happens vs what you expect to happen (with one or two specific VEVENT examples), that would be helpful.

**Comment by maxmanzero** [comment]
Certainly. The simplest example would be on November 11th 2016 which is the original issue the end user pointed out.
When we import the ICS we expect to see an event titled:
Chapel - Sr Talk Weiyi "Steven" Zhang & Royya Osouli 

But when I run the GetOccurences code I get:
Chapel
I think that there might be something funky going on with a past recurring event?
Honestly this is the first time I have ever worked with an Ical feed so I am pretty much a babe in the woods.

**Comment by maxmanzero** [comment]
Sorry I just realized you want a specific VEVENT:

If you open the ICS and go to line 1056 that begins the Event for November 11th. 

So this event appears properly in the ICS and when I use the LoadFromStream method and dump the Calendar.Events collection the event still appears normal, but once I call GetOccurences with the specified time frame from above the summary becomes Chapel with nothing else.
BEGIN:VEVENT
DTSTART:20161102T135000Z
DTEND:20161102T142000Z
DTSTAMP:20161219T192554Z
UID:9C59F520-7C36-4D1B-B373-02AAD10DBABF
RECURRENCE-ID:20161102T135000Z
CREATED:20160816T155858Z
DESCRIPTION:
LAST-MODIFIED:20161102T132029Z
LOCATION:All Saints Chapel
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Chapel - Sr Talk Weiyi "Steven" Zhang & Royya Osouli \n
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
BEGIN:VALARM
ACTION:NONE
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
X-WR-ALARMUID:0DBDC440-72CF-4029-98A0-328BF5F88672
UID:0DBDC440-72CF-4029-98A0-328BF5F88672
ACKNOWLEDGED:20161102T015001Z
X-APPLE-DEFAULT-ALARM:TRUE
END:VALARM
END:VEVENT

**Comment by maxmanzero** [comment]
Something just occurred to me that might shed some light on my ignorance with ical feed parsing. When I call GetOccurrences should I only be calling that to get recurring events? Should I be merging events found from that call with non-recurring events that are part of the feed?
