### ISSUE TITLE
GeographicLocationSerializer - incorrect float format

### ISSUE THREAD

**Issue by janousek** [ical-org/ical.net#202]
`var value = g.Latitude.ToString("0.000000") + ";" + g.Longitude.ToString("0.000000");`
Does not work like expected when you use culture with comma decimal separator (dot is only allowed separator).
Invariant culture should be specified here 
`var value = g.Latitude.ToString("0.000000", CultureInfo.InvariantCulture.NumberFormat) + ";" + g.Longitude.ToString("0.000000", CultureInfo.InvariantCulture.NumberFormat);`

**Comment by rianjs** [comment]
I'm not sure what you're saying. Which scenario applies to you?

* Expected: 1,2345 / Actual: 1.2345
* Expected: 1.2345 / Actual: 1,2345

**Comment by janousek** [comment]
The second one.

**Comment by rianjs** [comment]
Fix is in nuget package 2.2.23. Should be indexed in a few minutes.

https://www.nuget.org/packages/Ical.Net

**Comment by rianjs** [comment]
fc908561c83bb84cf6f014a488c5347c29a2fa91
