### ISSUE TITLE
CalendarProperty isn't properly serialized

### ISSUE THREAD

**Issue by rianjs** [ical-org/ical.net#209]
```csharp
[Test]
[Ignore("Calendar properties aren't being properly serialized")]
public void PropertySerialization_Tests()
{
    const string formatted =
@"FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 3.2//EN"">\n<HTML>\n<HEAD>\n<META NAME=""Generator"" CONTENT=""MS Exchange Server version rmj.rmm.rup.rpr"">\n<TITLE></TITLE>\n</HEAD>\n<BODY>\n<!-- Converted from text/rtf format -->\n\n<P DIR=LTR><SPAN LANG=""en-us""><FONT FACE=""Calibri"">This is some</FONT></SPAN><SPAN LANG=""en-us""><B> <FONT FACE=""Calibri"">HTML</FONT></B></SPAN><SPAN LANG=""en-us""><FONT FACE=""Calibri""></FONT></SPAN><SPAN LANG=""en-us""><U> <FONT FACE=""Calibri"">formatted</FONT></U></SPAN><SPAN LANG=""en-us""><FONT FACE=""Calibri""></FONT></SPAN><SPAN LANG=""en-us""><I> <FONT FACE=""Calibri"">text</FONT></I></SPAN><SPAN LANG=""en-us""><FONT FACE=""Calibri"">.</FONT></SPAN><SPAN LANG=""en-us""></SPAN></P>\n\n</BODY>\n</HTML>";

    var start = DateTime.Now;
    var end = start.AddHours(1);
    var @event = new Event
    {
        Start = new CalDateTime(start),
        End = new CalDateTime(end),
        Description = "This is a description",
    };
    var property = new CalendarProperty("X-ALT-DESC", formatted);
    @event.AddProperty(property);
    var calendar = new Calendar();
    calendar.Events.Add(@event);

    var serialized = new CalendarSerializer().SerializeToString(calendar);
    Assert.IsTrue(serialized.Contains("X-ALT-DESC;"));
}
```

Test case from http://stackoverflow.com/questions/41304898/how-do-i-create-an-html-formatted-ics-message-body-using-ical-net

**Comment by rianjs** [comment]
(Don't forget to delete the `[Ignore]` attribute when the bug is fixed!)

**Comment by beriniwlew** [comment]
I can't seem to debug the unit tests.  Am I missing something?

**Comment by poulerik-dk** [comment]
Im unsure if this bug still exists, since you have a typo in the assert (should be colon instead of semi-colon).

    Assert.IsTrue(serialized.Contains("X-ALT-DESC;"));
should be

    Assert.IsTrue(serialized.Contains("X-ALT-DESC:"));

If you change the typo, the test passes.

**Comment by alex3683** [comment]
I just stumbled over this while trying to find out how to set the X-ALT-DESC property for a HTML description. In my implementation I set the name of the property to include the type of the payload:

```c#
var property = new CalendarProperty("X-ALT-DESC;FMTTYPE=text/html", "<!DOCTYPE HTML PUBLIC ""-//W3..." );
```

This gives the expected result and should fix our test, since the original assertion is correct.

**Comment by angularsen** [comment]
The above workaround worked for me in Outlook to get formatted HTML in the calendar event.
I'm astounded that it still in 2023 doesn't just accept HTML in the event description as any sane calendar service should.

However, the HTML boilerplate does not seem necessary. In my testing, Outlook was quite happy with a bare minimum HTML document:
```html
<html>
<body>
<h1>Title</h1>
<b>Bold text</b>
</body>
</html>
```
