### ISSUE TITLE
MissingMethodException on iOS

### ISSUE THREAD

**Issue by danmiser** [ical-org/ical.net#217]
I'm using 2.3.1-xamarin-alpha in an iOS project. It works great in debug on the device, but as soon as I go AdHoc through TestFlight, an exception crashes the app. I saw the issue #216 and added the reference to System.Xml.Serialization in case that was the problem, and it didn't help.

I know in other PCL scenarios, you need to make a call to register that the library is using specific types. Is there such a call for ical.net? Or another way around this?

Here's the part of the exception right after I call
`var calendars = Calendar.LoadFromStream(reader);`

```
7 MyApp llvm_resume_unwind_trampoline (in a6066e706e24344f8e4224968f82744d) + 168
8 MyApp ical_net_Ical_Net_Serialization_iCalendar_Serializers_SerializerBase_GetService_System_Type (in a6066e706e24344f8e4224968f82744d) + 0
9 MyApp ical_net_Ical_Net_Calendar_LoadFromStream_System_IO_Stream_System_Text_Encoding_Ical_Net_Interfaces_Serialization_ISerializer (in a6066e706e24344f8e4224968f82744d) + 60
10 MyApp ical_net_Ical_Net_Calendar_LoadFromStream_System_IO_TextReader_Ical_Net_Interfaces_Serialization_ISerializer (in a6066e706e24344f8e4224968f82744d) + 112
11 MyApp ical_net_Ical_Net_Calendar_LoadFromStream_System_IO_TextReader (in a6066e706e24344f8e4224968f82744d) + 56
```

**Comment by rianjs** [comment]
This one-off xamarin alpha build is something I threw together one morning, and isn't supported in any way. It has no future. (It also doesn't have any of the many bugfixes that the standard versions have that I've patched since I published it.)

#28 is what you want to keep an eye on for non-Windows versions.
