### ISSUE TITLE
Duplicate property DESCRIPTION

### ISSUE THREAD

**Issue by Galapo** [ical-org/ical.net#218]
Version 2.2.26 has a bug that duplicates some fields. 

For example:
BEGIN:CALENDAR NAME
VERSION:2.0
BEGIN:NAME
CREATED:20170110T031603Z
DESCRIPTION:desc
DESCRIPTION:desc
DTEND:20171222T135019
DTSTAMP:20170110T031603Z
DTSTART:20170510T121531
LOCATION:location,
LOCATION:location
SEQUENCE:0
SUMMARY:summ
SUMMARY:summ
TRANSP:Transparent
UID:c7b91f5d-cbaf-4d8b-9f49-fcf25e85e4ce
UID:c7b91f5d-cbaf-4d8b-9f49-fcf25e85e4ce
END:NAME
END:CALENDAR NAME

I downgraded to 2.2.25 to solve the issue.

For your information this is how I'm using the API (pretty much as you have it):
 var item = new Event
            {
                DtStart = new CalDateTime(new DateTime.Now()),
                DtEnd = new CalDateTime(new DateTime.Now()),
                Summary = "summ", 
                Created = new CalDateTime(DateTime.UtcNow),
                Transparency = TransparencyType.Transparent,
                Description = "desc", 
                Name = "name",
                Location = "location"
                Uid = Guid.NewGuid().ToString(),
                IsAllDay = false
            };

            var calendar = new Calendar ();
            calendar.Events.Add(item);
            calendar.Name = "calendar name";

            var serializer = new CalendarSerializer(new SerializationContext());
            var serializedCalendar = serializer.SerializeToString(calendar);

**Comment by rianjs** [comment]
Thanks for the reminder -- I knew this bug existed, and was working on it, but forgot to unpublish the nuget package.

It's fallout from deep copy work that I'm doing, so I'm going to close this ticket, #214 and #149 are the canonical tickets for this.
