### ISSUE TITLE
GetOccurrences() ignores parallel events

### ISSUE THREAD

**Issue by lngr** [ical-org/ical.net#222]
Tested with 2.2.19 and latest stable 2.2.28.

I have this very simple calendar definition, which includes two parallel, weekly VEVENTS occurring at the exact same time (2017-01-17 15:20:00 - 2017-01-17 15:50:00 in our local TZ, RRULE:FREQ=WEEKLY):

```
BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:1
DTEND;TZID=Europe/Berlin:20170117T155000
DTSTAMP:20170116T145206Z
DTSTART;TZID=Europe/Berlin:20170117T152000
RRULE:FREQ=WEEKLY
SEQUENCE:0
SUMMARY:Event No 1
UID:395336de-bb71-b380-1852-84efc99b23c1
END:VEVENT
BEGIN:VEVENT
DESCRIPTION:2
DTEND;TZID=Europe/Berlin:20170117T155000
DTSTAMP:20170116T145221Z
DTSTART;TZID=Europe/Berlin:20170117T152000
RRULE:FREQ=WEEKLY
SEQUENCE:0
SUMMARY:Event No 2
UID:086be668-05e4-7507-54dd-1da23646dabd
END:VEVENT
END:VCALENDAR
```

Note that the UIDs of the VEVENTs are different.

However, the following code only returns occurrences of "Event No 1" (UID  395336de-bb71-b380-1852-84efc99b23c1):

```
byte[] byteArray = Encoding.UTF8.GetBytes(calString);
MemoryStream stream = new MemoryStream(byteArray);
var cal = Calendar.LoadFromStream(stream, Encoding.UTF8);

foreach (var o in cal.GetOccurrences(DateTime.Now, DateTime.Now.AddMonths(1)))
{
    Console.WriteLine(" ==> " +  ((Event)o.Source).Summary + " @ " + o.Period.StartTime + " / " + o.Period.StartTime.AsUtc);
}
```

This produces the following output:

```
 ==> Event No 1 @ 17.01.17 15:20:00 Europe/Berlin / 17.01.17 14:20:00
 ==> Event No 1 @ 24.01.17 15:20:00 Europe/Berlin / 24.01.17 14:20:00
 ==> Event No 1 @ 31.01.17 15:20:00 Europe/Berlin / 31.01.17 14:20:00
 ==> Event No 1 @ 07.02.17 15:20:00 Europe/Berlin / 07.02.17 14:20:00
 ==> Event No 1 @ 14.02.17 15:20:00 Europe/Berlin / 14.02.17 14:20:00
```

If I slightly change the DSTART of event No 2, e.g. to (only changed the last char from 0 to 1):
```
DTSTART;TZID=Europe/Berlin:20170117T152001
```
The output is as expected:
```
 ==> Event No 1 @ 17.01.17 15:20:00 Europe/Berlin / 17.01.17 14:20:00
 ==> Event No 1 @ 24.01.17 15:20:00 Europe/Berlin / 24.01.17 14:20:00
 ==> Event No 1 @ 31.01.17 15:20:00 Europe/Berlin / 31.01.17 14:20:00
 ==> Event No 1 @ 07.02.17 15:20:00 Europe/Berlin / 07.02.17 14:20:00
 ==> Event No 1 @ 14.02.17 15:20:00 Europe/Berlin / 14.02.17 14:20:00
 ==> Event No 2 @ 17.01.17 15:20:01 Europe/Berlin / 17.01.17 14:20:01
 ==> Event No 2 @ 24.01.17 15:20:01 Europe/Berlin / 24.01.17 14:20:01
 ==> Event No 2 @ 31.01.17 15:20:01 Europe/Berlin / 31.01.17 14:20:01
 ==> Event No 2 @ 07.02.17 15:20:01 Europe/Berlin / 07.02.17 14:20:01
 ==> Event No 2 @ 14.02.17 15:20:01 Europe/Berlin / 14.02.17 14:20:01
```
Modifying DTEND similarly has the same positive effect. 

The bug also occurs when using UTC timestamps.

**Comment by rianjs** [comment]
I think I know why this happens, as I was doing work in the area yesterday... Recurrence sets contain `Period`s, which are simple objects: Start, End, Duration. `GetHashCode` is implemented using those properties. Sets allow no duplicates, and `Period` has no way of distinguishing a period from Event A from an identical period associated with Event B. This is fine when calling `Event.GetOccurrences()`, but not when you do `Calendar.GetOccurrences()`.

I haven't tested this, but as a workaround, you may want to create a `Dictionary<string, HashSet<IPeriod>>` and use `Event.Uid` as your dictionary key:

```csharp
var calOcc = yourCal.Events.ToDictionary(e => e.Uid, e => e.GetOccurrences(searchStart, searchEnd));
```

Or if you're working with more than `Event`s:

```csharp
var occ = yourCal.Children
    .OfType<IRecurrable>
    .ToDictionary(r => r.Uid, r => r.GetOccurrences(searchStart, searchEnd));
```

What we need is an internal identifier that ties a `Period` to its parent recurrable (`Alarm`, `Event`, etc.) that can be used in `GetHashCode`.

**Comment by lngr** [comment]
Thanks. I hoped it could be due to the GetHashCode and the HashSet, but couldn't find the position where the hashes are generated. `Period` makes sense.

Wouldn't it suffice to use the parent's `UID`?

**Comment by rianjs** [comment]
Yes, see workaround above. (Ideally a Period would reference that Uid by default.)

**Comment by rianjs** [comment]
Oh, you can throw an `AsParallel` in there to speed things up:

```csharp
var calOcc = yourCal.Events
    .AsParallel()
    .ToDictionary(e => e.Uid, e => e.GetOccurrences(searchStart, searchEnd));
```

Occurrence computation is expensive, but can be done concurrently.

**Comment by lngr** [comment]
The workaround works great.
