### ISSUE TITLE
Alarm not setting on event

### ISSUE THREAD

**Issue by Priyank-Kotiyal** [ical-org/ical.net#227]
**Nuget version:** Ical.Net 2.2.30
**observed behavior:** Alarm not setting
**expected behavior:** Alarm should set
Following is the Alarm component created after serialising-:
```
BEGIN:VALARM
ACTION:Display
DESCRIPTION:Upcoming Event
TRIGGER:-PT5M
X-WR-ALARMUID:4EA98594-D604-418C-8A79-A860F92A6208
END:VALARM
```
But if I replace "Display" to "DISPLAY" alarm is setting.

**Comment by noli44** [comment]
Temporary fix for anyone interested. Create a new class that inherits from Alarm and set the properties yourself. Easiest way I found to do so is with the example below.

<code>
        public class CompatibleAlarm : Alarm {
                 public string AlarmAction {
                         get { return Properties.Get<string>("ACTION"); }
                         set { Properties.Set("ACTION", value); }
                 }
         }
</code>

not sure what is up with the formatting.
