### ISSUE TITLE
Exception on reading a "tabbed" file

### ISSUE THREAD

**Issue by freica** [ical-org/ical.net#233]
I get a "MismatchedTokenException" {"expecting \"END\", found '\t'"} on reading a ics-file using [HTAB][HTAB][LF], see the attached file or [https://www.schulferien.eu/downloads/ical4.php?land=2&type=1&year=2017](url).
I don't know, if this file is full based on the RFC, but Outlook for example can read it.

Thanks in advance
Freica

![tabbedfile](https://cloud.githubusercontent.com/assets/25507027/22552722/64470992-e95a-11e6-924b-d299174ba49a.png)

**Comment by rianjs** [comment]
Outlook opens a lot of files that it shouldn't. I don't intend for ical.net to interop with badly-behaved programs: those developers should fix their code.

I don't know what created that ical file (`PRODID:-//hacksw/handcal//NONSGML v1.0//EN`) but it's not valid ical:

* Line endings should be CR-LF (`\r\n`), not LF (which is just `\n`)
* Blank lines aren't normal
* Blank lines with tabs in them are even less normal
* Several lines are too long -- they should be "[folded](https://tools.ietf.org/html/rfc5545#section-3.1)" at 75 characters. E.g.: `DESCRIPTION: Alle Angaben ohne Gewähr. Weitere Infos auf www.schulferien.eu`

Have a look for yourself:
https://icalendar.org/validator.html
