### ISSUE TITLE
update interval when serializing a calendar?

### ISSUE THREAD

**Issue by mgamache** [ical-org/ical.net#234]
I want to set a high update rate in my outlook subscribers, so it refreshes my published iCal feed every few minutes (mainly during testing).  I see references to X-PUBLISHED-TTL, but, that may not be supported (as it's an MS only standard). Is there a way to specify the update frequency when publishing an iCal feed? Sorry if this is obvious and I am just missing it.

**Comment by rianjs** [comment]
As far as I know, there's no way to represent how often a client should refresh an ical feed in RFC-5545. I suspect Microsoft would have used the standard parameter if there was.

**Comment by lauxjpn** [comment]
This is part of [RFC 7986: New Properties for iCalendar](https://tools.ietf.org/html/rfc7986), dated October 2016.

_(From [5.7. REFRESH-INTERVAL Property](https://tools.ietf.org/html/rfc7986#section-5.7))_

>Property Name:  REFRESH-INTERVAL
>
>Purpose:  This property specifies a suggested minimum interval for polling for changes of the calendar data from the original source of that data.
>
>Value Type:  DURATION -- no default
>
>[...]
>
>Example:  The following is an example of this property:
>
>`REFRESH-INTERVAL;VALUE=DURATION:P1W`

**Comment by taylorchasewhite** [comment]
Can this be reopened?
