### ISSUE TITLE
GetOccurrences ignore some day range when I use weekly occurrence

### ISSUE THREAD

**Issue by kycuong2208** [ical-org/ical.net#235]
Hi all

I got the issue when I use Ical.net to get list Occurrences in calendar. List Occurrences will miss some event in day range such as the event from 1/1/2019 to 1/7/2019. My example below:

```csharp
var calendar = new Calendar();
var rule = new RecurrencePattern("FREQ=WEEKLY;BYDAY=SU,MO,TU,WE,TH,FR,SA");
var startDateTemp=new DateTime(2018,12,30);
var endDateTemp = new DateTime(2018, 12, 31);
var vEvent = new Event
{
    DtStart = new CalDateTime(startDateTemp),
    DtEnd = new CalDateTime(endDateTemp),
    RecurrenceRules = new List<IRecurrencePattern>{ ruleTemp }
};
calendar.Events.Add(vEvent);
var startDate= new DateTime(2019, 1, 1);
var endDate = new DateTime(2019, 1, 6);
var occurrences = calendar.GetOccurrences(startDate, endDate);
```

=> and we will got list occurrences don't have any records.

Note: If I use daily occurrence, this issue not happen. When I tested with another date( not in range 1/1/2019 to 1/6/2019) , the system can execute exactly.

Please give me your advices.

Thanks

**Comment by rianjs** [comment]
@DmitriySelischev's fix published in nuget v2.2.33.

https://www.nuget.org/packages/Ical.Net/2.2.33
