### ISSUE TITLE
API changes for v3

### ISSUE THREAD

**Issue by rianjs** [ical-org/ical.net#24]
Get rid of:
- ~~LoadFromFile (replacement = strings)~~
- ~~LoadFromUri: the web is a lot different than it used to be. Having ical.net handle the download logic takes specific dependencies on specific framework elements. It reduces the library's ability to iterate. I would prefer to leave `HttpClient` out of it, which some client profiles may not support. Application developers can provide their own download-from-source implementation if they wish.~~

VTimeZone:
- ~~Just make the user specify a time zone string. Get rid of the `FromSystemTimeZone` and `FromLocalTimeZone` stuff which isn't well-defined in a cross-platform world.~~

Attachment:
- ~~`Data` properties on `Attachment`s should be getter-only~~
- There should be a constructor flavor that takes a `byte[]` that does the right thing WRT to base64-encoding on both serialization and deserialization

Misc:
- Target [netstandard 1.1](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms)

**Comment by khalidabuhakmeh** [comment]
Getting rid of `HttpClient` dependencies is a good idea. As long as iCal.NET can produce a `byte[]` I think most, if not all developers will be happy.

**Comment by rianjs** [comment]
You may be interested in this:

http://rianjs.net/2016/07/api-changes-for-ical-net-v3

**Comment by rianjs** [comment]
(Moved from https://github.com/rianjs/ical.net/issues/37 )

> I am not hugely familiar with the library, and I may have missed important features of the library in which case I apologise. Assigning values to properties with a limited number of valid values under the spec seems inconsistent.
> 
> The Event property Class is a string, and the developer must know (or look up) valid values are "PUBLIC" or "PRIVATE", the same for an Attendee property Role (e.g. "REQ-PARTICIPANT").
> 
> the Event properties Transparency and Status are Enums.
> 
> An Attendee ParticipationStatus string property can be assigned from the const strings in the ParticipationStatus namespace. The same applies to the Calendar Method property and the CalendarMethods namespace
> 
> It would seem ideal if the above 6 properties all had a similar method of asignment.
> 
> Thanks
> @mcshaz

**Comment by mcshaz** [comment]
another part of the potential roadmap, but should the stated objective of V3 be to offer compliance with RFC 5545 ([see differences with RFC 2445](https://tools.ietf.org/html/rfc5545#appendix-A))?

**Comment by mcshaz** [comment]
Properties such as Created, LastModified &  DtStamp are meant to be UTC under the spec. Once you have worked out how you want to implement IDateTimes, it would be worth considering how to convey this to the user is not familiar with the spec. options include:
- Changing names to CreatedUtc, LastModifiedUtc etc.
- Having some kind of UtcDateTime type which inherits from CalDateTime or its new & improved form.

**Comment by rianjs** [comment]
Apparently GetOccurrences is a thing at the `CalendarCollection` level... that seems wrong. C.f. #148

**Comment by rianjs** [comment]
Calendar Name property is public, but should probably be internal. Via email:

``` csharp
Event Test = new Event();
Test.Description = "Some additional info";
Test.Name = "a NAme"; 
Test.Summary = "a Test"; //The real Name 
var Time = new DateTime(2016, 10, 7, 8, 0, 0);
Test.DtStart = new CalDateTime(Time);
Test.Transparency = TransparencyType.Transparent;
Test.IsAllDay = true;
var calendar = new Calendar();
calendar.Events.Add(Test);
calendar.Name = "ANAmeForACalender";

var serializer = new CalendarSerializer(new SerializationContext());
var serializedCalendar = serializer.SerializeToString(calendar);
```

I would like to tell you that in version 2.2.14 of Ical.Net the Name property of the class Event and Calender should be private. Because it leads to an issue with the .ics format.

I used this service to validate the generated ics: http://icalendar.org/validator.html

Here is the generated example:

```
BEGIN:DerKalender
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
BEGIN:TheTest
DESCRIPTION:Das ist die Beschreibung
DTEND:20161008T213910
DTSTAMP:20161006T193910Z
DTSTART:20161007T213910
SEQUENCE:0
SUMMARY:Der Name
UID:797aed96-d86f-45ef-9ade-4939f23c85e1
END:TheTest
END:DerKalender
```

And this works:

```
BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:Das ist die Beschreibung
DTEND:20161008T213910
DTSTAMP:20161006T193910Z
DTSTART:20161007T213910
SEQUENCE:0
SUMMARY:Der Name
UID:797aed96-d86f-45ef-9ade-4939f23c85e1
END:VEVENT
END:VCALENDAR
```

**Comment by rianjs** [comment]
Hey, we're on v4 now!
