### ISSUE TITLE
IDateTime.ToEpochTime Returns Incorrect Value when TimeZone specified

### ISSUE THREAD

**Issue by jtillman** [ical-org/ical.net#240]
When constructing a CalDateTime that specifies a TimeZone, ToEpochTime returns incorrect values.

Example:
`var calDateTime = new CalDateTime(2017, 2, 24, 22, 0, 0, "Pacific Standard Time");
 Console.WriteLine(calDateTime.ToEpochTime();
// 1487973600 or 2pm (instead of 10pm) PST`

Suggested Fix is to first use `TimeZoneInfo.ConvertTime` from the specified timezone to UTC before using the `Ticks` property.

```
public static int ToCorrectEpochTime(this IDateTime dt)
{
  TimeZoneInfo tzInfo = TimeZoneInfo.FindSystemTimeZoneById(dt.TimeZoneName);
  DateTime originalDateTime = new DateTime(year:dt.Year, month: dt.Month, day: dt.Day, hour: dt.Hour, minute: dt.Minute, second: dt.Second);
  DateTime utcDateTime = TimeZoneInfo.ConvertTime(priginalDateTime, tzInfo, TimeZoneInfo.Utc);
  // Now Do Epoch Math w/utcDateTime.Ticks
}
```

**Comment by rianjs** [comment]
There is no `ToEpochTime()` in ical.net. In fact, the text "epoch" doesn't appear anywhere. Did someone write an extension method in your code base that's buggy?

**Comment by jtillman** [comment]
🤕 You're write! Sorry for the noise... I'll go fuss at someone else now 😄
