### ISSUE TITLE
Alarm not respecting specified TimeSpan

### ISSUE THREAD

**Issue by rpiette** [ical-org/ical.net#243]
My serialized calendar is:

"BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:test description
DTEND;VALUE=DATE:20170312
DTSTAMP:20170310T205044Z
DTSTART;VALUE=DATE:20170311
LOCATION:test location
SEQUENCE:0
SUMMARY:test summary
UID:dc3573bf-0ae3-4084-a582-048ac75c5002
BEGIN:VALARM
ACTION:Display
TRIGGER:-PT1H
END:VALARM
END:VEVENT
END:VCALENDAR
"

But when I open the attachment in Outlook, the resulting event has an alarm of 18 hours instead of 1 hour?

**Comment by rianjs** [comment]
Hmm, interesting.

This works as expected:
```csharp
[Test, Category("Alarm")]
public void AlarmDuration()
{
    const string ics = @"BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:test description
DTEND;VALUE=DATE:20170312
DTSTAMP:20170310T205044Z
DTSTART;VALUE=DATE:20170311
LOCATION:test location
SEQUENCE:0
SUMMARY:test summary
UID:dc3573bf-0ae3-4084-a582-048ac75c5002
BEGIN:VALARM
ACTION:Display
TRIGGER:-PT1H
END:VALARM
END:VEVENT
END:VCALENDAR";

    var e = Calendar.Load(ics).Events.Single();
    var alarmTrigger = e.Alarms.Single().Trigger;
    Assert.AreEqual(alarmTrigger.Duration, TimeSpan.FromHours(-1));
}
```

Let me see if I can see how Outlook creates reminder triggers in ics...

**Comment by rianjs** [comment]
Yeah, I just did an Outlook test with a 15 minute reminder, and it worked fine using the example code above.
