### ISSUE TITLE
[.NET Core] NullReferenceException during Event serialization

### ISSUE THREAD

**Issue by remyjette** [ical-org/ical.net#253]
(Forked from #23)

Creating a simple calendar with a single calendar event (basically the sample in https://github.com/rianjs/ical.net/wiki without the recurrence rules) in a .NET Core console app fails to serialize.

I did some debugging, looks like the `actualEvent.Properties.Remove("DURATION")` in `EventSerializer.cs` removes the DURATION from `_dictionary`, but not from `_lists`, causing the `_lists` entry to be set to null.
Since `_lists` is what is used to create the enumerator, this null entry is included when using LINQ extension methods.

This means that during serialization, in `ComponentSerializer.SerializeToString()` the following throws a NullReferenceException because p is null:

    var properties = c.Properties.OrderBy(p => p.Name).ToList();

Sample code to reproduce is below, using Microsot.NETCoreApp 1.1.1:

    var now = DateTime.Now;
    var later = now.AddHours(1);
    var e = new CalendarEvent
    {
        DtStart = new CalDateTime(now),
        DtEnd = new CalDateTime(later)
    };
    var calendar = new Calendar();
    calendar.Events.Add(e);
    var serializer = new CalendarSerializer(new SerializationContext());
    var serializedCalendar = serializer.SerializeToString(calendar);

**Comment by Mfron-42** [comment]
@remyjette  what is your solution ?

**Comment by remyjette** [comment]
I mean, a quick hack would be to change

    var properties = c.Properties.OrderBy(p => p.Name).ToList();

to

    var properties = c.Properties.Where(p => p != null).OrderBy(p => p.Name).ToList();

But I'm not planning on submitting a PR to change that line because it's just that - a hack. The underlying issue is that when `GroupedListEnumerator` is enumerating the values of the `CalendarPropertyList` that contains the properties of the event, it's including a `null` for the removed `DURATION` property rather than skipping it. I haven't yet had time to dig into this further, but that's my findings so far. Hopefully I'll have soon have some more time to investigate this so I can submit a PR with an actual fix rather than the hack I mentioned above.

**Comment by Mfron-42** [comment]
Ok perfect thx, im waiting for the next release ;)

Ps : i suggest maybe : var properties = c.Properties.OrderBy(p => p?.Name).ToList ();
 
If the problem is just this line ? Just because im loving this operator <3

**Comment by Mfron-42** [comment]
Ps : we can 

var properties = c.Properties.OrderBy(p => p?.Name).ToList ();

**Comment by Mfron-42** [comment]
I suggest ?

**Comment by remyjette** [comment]
The issue isn't that line - as mentioned above, it's with the `GroupedListEnumerator`. If you wanted to patch it locally to get your program to run you could use the hack I mentioned above, but that's not a real fix. It's quite possible there are parts of the program that could be affected by this, which wouldn't be helped by just patching one of the symptoms.

Also, if you were to use the `?.` null-conditional operator in the `OrderBy` clause, that wouldn't fix it as it would leave the null value in the collection, causing the NRE to simply be moved down a few lines (it'd get thrown in the foreach loop two lines later on the `p.GetType()` call)

**Comment by jchannon** [comment]
Think this may relate to #260

**Comment by rianjs** [comment]
@remyjette - does your PR ( #270 ) solve this issue?

**Comment by remyjette** [comment]
Yep! Closing this issue.

Sorry I hadn't gotten a chance to follow up to your comment in the PR about testing and checking v2, as you saw it had diverged widely so I just hadn't had the time to verify the changes in both. But thank you for merging!

**Comment by rianjs** [comment]
Awesome!

Published in Ical.Net 3.0.9-net-core-beta:
https://www.nuget.org/packages/Ical.Net/

**Comment by medokin** [comment]
Using 3.0.14
```
NullReferenceException in Ical.Net.Serialization.iCalendar.Serializers.Components.EventSerializer.SerializeToString in Ical.Net.dll
```

EDIT: Nevermind
The works after I removed:

```c#
Class = "PUBLIC",
```
