### ISSUE TITLE
Event.Duration property does not reflect changes made with IsUniversalTime flag

### ISSUE THREAD

**Issue by sonyisda1** [ical-org/ical.net#254]
In my example, I am creating a new event based from pre-existing start/end times.  I am working solely with UTC.

I have the following dates already set
```
DateTime start = new DateTime(2017, 3, 23, 12, 0, 0);
DateTime end = new DateTime(2017, 3, 23, 16, 0, 0);
```

The calEvent.Duration from the following code with display {09:00:00} (9 hours)
```
calEvent = new Event();
calEvent.DtStart = new CalDateTime(start);
calEvent.DtStart.IsUniversalTime = true;
calEvent.DtEnd = new CalDateTime(end);
calEvent.DtEnd.IsUniversalTime = true;
```
It gets the 9 hours since the span is 4 hours + before I set IsUniversalTime flag it presumes local time (since it is not explicitly set) in which I am currently -5:00 from UTC in Central Daylight Time.

The calEvent.Duration from the following code with display as anticipated {04:00:00} (4 hours) since I specify the kind as UTC.
```
DateTime start = new DateTime(2017, 3, 23, 12, 0, 0);
DateTime end = new DateTime(2017, 3, 23, 16, 0, 0);
calEvent = new Event();
calEvent.DtStart = new CalDateTime(DateTime.SpecifyKind(start, DateTimeKind.Utc));
calEvent.DtEnd = new CalDateTime(DateTime.SpecifyKind(end, DateTimeKind.Utc));
```

Is there a way for force a re-determination of the Duration property?  Or do I just need to proceed like in my second example with explicitly specifying the DateTime.Kind as UTC so the Event knows it is working in UTC when setting DtStart and DtEnd?

**Comment by rianjs** [comment]
This should be much better in v4: https://www.nuget.org/packages/Ical.Net/4.0.0
