### ISSUE TITLE
Opening icloud event on outlook client shows Free/busy status as "Out off office" instead of busy

### ISSUE THREAD

**Issue by Priyank-Kotiyal** [ical-org/ical.net#255]
Nuget version: Ical.Net 2.2.30
observed behavior: Status sets as OOF
expected behavior: Status should set as BUSY

BEGIN:VCALENDAR
PRODID:-//Apple Inc.//iCal 5.0.2//EN
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:Test
DTEND:20170324T104500Z
DTSTAMP:20170324T093907Z
DTSTART:20170324T103000Z
SEQUENCE:0
STATUS:Confirmed
SUMMARY:Test
UID:FC97A241-EC79-4848-8842-3920C58EE520
END:VEVENT
END:VCALENDAR

Solution :
Need to add X-MICROSOFT-CDO-BUSYSTATUS property.
event.AddProperty("X-MICROSOFT-CDO-BUSYSTATUS", "BUSY");

**Comment by rianjs** [comment]
You discovered the answer on your own, I see:

http://stackoverflow.com/questions/42996237/opening-icloud-event-created-using-ical-net-on-outlook-client-shows-free-busy

**Comment by Priyank-Kotiyal** [comment]
Yes. 
Thanks
