### ISSUE TITLE
[.NET Core] GetOccurrences caused a StackOverflow error.

### ISSUE THREAD

**Issue by adammoroff** [ical-org/ical.net#257]
Version: 3.0.1-net-core-alpha
When invoking the GetOccurences function of the CalendarEvent object application crashes resulting from a StackOverflow error. 

The program '[9452] dotnet.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

**Comment by rianjs** [comment]
Do you have sample code?

**Comment by adammoroff** [comment]
Hi Rian, I have prepard a sample app (attached)  To repeat the error click the "About" link at the top of the page.  This will invoke the About controller method.  Let me know if Ive missed something. Cheers Adam
[GetOccurencesIssue.zip](https://github.com/rianjs/ical.net/files/891943/GetOccurencesIssue.zip)

**Comment by rianjs** [comment]
Published in Ical.Net 3.0.9-net-core-beta:
https://www.nuget.org/packages/Ical.Net/

**Comment by danmiser** [comment]
Thanks much!
