### ISSUE TITLE
[.NET Core] Support combination of NodaTime 2.0.0 and .NET 4.6.X

### ISSUE THREAD

**Issue by janousek** [ical-org/ical.net#258]
There is currently no version of ical.net that can be used together with NodaTime 2.0.0 and .NET 4.6.X.
Version 2 requires NodaTime 1.3.1.
Version 3 supports NodaTime 2, but it requires netstandard1.6 that is not compatible with .NET 4.6.X.

Please create version that will work with NodaTime 2.0.0 and .NET 4.6.X.

I believe that there is several possibilities:
1) upgrade version of .NET Standard from 1.6 to 2.0.
2) downgrade version of .NET Standard from 1.6 to 1.4.
3) create new release of ical.net v2 with NodaTime 2.0.0 as a dependency.

**Comment by rianjs** [comment]
Interesting, thanks.

Notes to myself:

* ical.net v2 should NodaTime 1.*?
* ical.net v3 should use NodaTime 2.*?

[Have they figured out the story with BCL time zones yet?](http://stackoverflow.com/questions/38190911/where-is-the-bcl-datetimezoneprovider-in-the-net-core-implementation-of-nodatim)

**Comment by rianjs** [comment]
Re-titling and labeling based on my thoughts above. ^^

**Comment by rianjs** [comment]
Is this still a bug? net-core is building, and the tests are running.

**Comment by janousek** [comment]
Everything works. It can be closed.
