### ISSUE TITLE
Evaluate method of RecurrencePatternEvaluator class returns occurrences with startDate less then from date

### ISSUE THREAD

**Issue by ycharniauski** [ical-org/ical.net#283]
Hei

![ical](https://cloud.githubusercontent.com/assets/22836933/26313062/5f989ba0-3f12-11e7-8737-835cbc0efb63.png)

Why does **RecurrencePatternEvaluator.Evaluate(...)** method returns occurrences less then from date?
Is that a bug?
I expect that all occurences should be between start and end dates.

**Comment by pako1337** [comment]
Yea, hit as real hard yesterday on test machine, resulting in some fun behaviour with infinite loop :)

What's up with that? Is it by design and are we misunderstanding it, or is is an issue with lib?

**Comment by rianjs** [comment]
Can you re-open with some example ics text and sample code?

**Comment by renatogbp** [comment]
Can you re-open this issue? I am having the same problem. There's a test case:

	[Fact]
	public void Evaluate_WhenStartSearchTimeIsGreaterThanReferenceDate_ShouldNotIncludeDateBeforeSearchStartTime()
	{
		// arrange
		var rrule = new Ical.Net.DataTypes.RecurrencePattern("FREQ=DAILY;COUNT=6");
		var recurrenceEvaluator = new Ical.Net.Evaluation.RecurrencePatternEvaluator(rrule);
		var reference = new Ical.Net.DataTypes.CalDateTime(DateTime.UtcNow.AddDays(-3));
		var searchStartTime = DateTime.UtcNow;
		var searchEndTime = DateTime.UtcNow.AddDays(10);

		// act
		var occurrences = recurrenceEvaluator.Evaluate(reference, searchStartTime, searchEndTime, false);

		// assert
		Assert.False(occurrences.Select(x => x.StartTime.AsDateTimeOffset).Where(date => date <= searchStartTime).Any());
	}
