### ISSUE TITLE
New ical standards with the Z indicator vs. TZID=

### ISSUE THREAD

**Issue by seraphx2** [ical-org/ical.net#284]
So I was doing some testing and one of my users was having problems. Him and another guy troubleshot it down to the fact I was assigning TZID and not using Z. The thing is, the CalDateTime() method doesn't seem to automatically add Z onto the end. Is there a way to force the Z at the end?

This is my current line of code: new CalDateTime(fleet.Time.AddMinutes(-fleet.Offset), "UTC")

What woudl I need to do to drop the UTC and have the Z at the end instead?

**Comment by rianjs** [comment]
This is a duplicate of #263, so I'm going to close it up.

Answer: I'm going to put the `Z` back. It's more disruptive than I would have imagined.
