### ISSUE TITLE
Calendar Comparison

### ISSUE THREAD

**Issue by andrewcartwright1** [ical-org/ical.net#289]
Hi,

I'm looking to compare 2 calendars together for differences between the events (there is about 2000+ events), I was just wondering what you would suggest for this?

I have been considering using the `Uid` property to compare? but can imagine this will be slow.

Currently I'm using `.Except` but have noticed this looks to be missing some newly created events

**Comment by rianjs** [comment]
Can you re-ask this on StackOverflow so I can answer it in a more Google-friendly way?

**Comment by andrewcartwright1** [comment]
https://stackoverflow.com/questions/44404984/ical-net-calendar-comparison As requested

**Comment by rianjs** [comment]
https://stackoverflow.com/a/44443738/689185

**Comment by rianjs** [comment]
And a wiki page: https://github.com/rianjs/ical.net/wiki/Comparing-collections-of-calendar-events

**Comment by andrewcartwright1** [comment]
Very helpful! Thank you very much.
