### ISSUE TITLE
Recurrence rule patterns (ByMonthDay, etc) are not set, and aren't serialized

### ISSUE THREAD

**Issue by SarahU** [ical-org/ical.net#291]
Hello 

Please could you upload an example of how to create a recurring event that happens on the same [day in month] every month? For example, the 5th of every month. Like a debit or stop order?

Thank you.

**Comment by rianjs** [comment]
Sure:

```csharp
var rrules = new RecurrencePattern(FrequencyType.Monthly)
{
    ByMonthDay = new List<int> { 5 },  // Your day of the month goes here
};
var monthlyOnDay = new Event
{
    Start = new CalDateTime(_now),
    End = new CalDateTime(_now.AddHours(1)),
    RecurrenceRules = new List<IRecurrencePattern> { rrules },
};
```

**Comment by rianjs** [comment]
I incorrectly thought there was a bug. That's what I get for programming while sick. :\

**Comment by rianjs** [comment]
I have added this example to the [Working with recurring elements wiki page](https://github.com/rianjs/ical.net/wiki/Working-with-recurring-elements)

**Comment by SarahU** [comment]
Thank you! :)
