### ISSUE TITLE
Get occurrences from X Date for X times

### ISSUE THREAD

**Issue by samir-syed** [ical-org/ical.net#299]
So I have a situation where I want to get occurrences for a task object.

The data I have is:

DateTime (the start of the recurrences), x times (number of times the task should recur) and then the type of recurrence which could be any of the following:

**Daily**:
Daily, Every [ X ] days
Every Weekday

**Weekly**:
Recur every [ X ] weeks on: [ Sunday, Monday ...... Saturday ]

**Monthly**:
- Day [ X ] of every [ X ] month(s)
- The [ (first, second, third, fourth, last) ], [ (day, weekday, weekendday, sunday, monday.....satuday) ] of every [ X ] month(s)
 
**Yearly**:
- On [ (Jan, Feb .....Dec) ] - [ X ]
- On the [ First, second, third, fourth, last ] - [day, weekday, weekendday, sunday, monday.....saturday ] of [ Jan, feb .... dec ]

If I have a "Recur until" date then I got it working but I cannot seem to get the correct end date for the engine to throw out the occurrences when I have a "Repeat for X Times" where X is an integer (1,2,3...)

Any idea of how the above could be achieved?

**Comment by rianjs** [comment]
This wiki page has several closely-related examples:
https://github.com/rianjs/ical.net/wiki/Working-with-recurring-elements

**Comment by samir-syed** [comment]
Yes it does but all of the examples have a DtEnd (end date) property which I don't. I have a repeat for X times. Is there a property to set the number of occurrences to return? I will have to assume the end date?

**Comment by rianjs** [comment]
* Every event has a start and end datetime
* Recurrence rules are specified separately from the event's start and end datetimes

So:

1. Specify the recurrence rules. Instead of `Until`, use `Count` with a `interval` specified.
2. Create an event and associate the recurrence rules with that event (examples on that wiki page)
3. Search for occurrences between X and Y datetimes (examples on that wiki page)

Here are some example recurrence rules:

```csharp
var everyThird = new RecurrencePattern(FrequencyType.Daily, interval: 3)
{
    Count = 10, // Every third day, for 10 occurrences
};

var byMonthDay = new RecurrencePattern(FrequencyType.Monthly, interval: 1)
{
    ByMonthDay = new List<int> { 3, 5 },    // Day 3 and day 5 of every month
    Count = 5,  // For 5 months
};
```

Then you would associate them with an event:

```csharp
var vEvent = new Event()
{
    DtStart = new CalDateTime(_now),
    DtEnd = new CalDateTime(_now.AddHours(1)),
    RecurrenceRules = new List<IRecurrencePattern>
    {
        byMonthDay,
        //You could also add everyThird here, too
    }
};
```

**Comment by samir-syed** [comment]
So I have this test where I want to get occurrences for - EVERY TUESDAY AND WEDNESDAY FOR EVERY 2 WEEKS FOR 2 TIMES

I am expecting 5 occurrences even though I gave a future date. Shouldn't the library return just the occurrences based on the recurrence rules? 

```
RecurrencePattern weeklyPattern = new RecurrencePattern
            {
                FirstDayOfWeek = DayOfWeek.Sunday,
                Frequency = FrequencyType.Weekly,
                Interval = 2,
                ByDay = new List<IWeekDay> { new WeekDay(DayOfWeek.Tuesday), new WeekDay(DayOfWeek.Wednesday) }
            };

            Event ev = new Event
            {
                DtStart = new CalDateTime(DateTime.Parse("2017-06-25T07:00")),
                DtEnd = new CalDateTime(DateTime.Parse("2017-07-28T08:00")),
                RecurrenceRules = new List<IRecurrencePattern> { weeklyPattern }
            };

            var occurrences = ev.GetOccurrences(DateTime.Parse("2017-06-25"), DateTime.Parse("2017-07-28"));

            Assert.IsTrue(occurrences.Count == 5);
```

I gave an end date of 28th July 2017 which is an extra week ahead but then the rules I gave to the event is with an interval of 2. Shouldn't it return 5 dates? Instead it returns 7 dates because the 2 dates it gets from the extra week.

Am I mis-understanding something here?

Note: I supply the extra week because I assume an end date.

**Comment by rianjs** [comment]
```csharp
DtStart = new CalDateTime(DateTime.Parse("2017-06-25T07:00")),
DtEnd = new CalDateTime(DateTime.Parse("2017-07-28T08:00")),
```

This is wrong. Your event doesn't have a start datetime of 6/25 @ 0700 and an end datetime of 7/28 @ 0800. That would be an event that's over month long. Don't try to be smart about figuring out the end time of the last occurrence. Let the library do that.

Your DtEnd should be 6/25 @ 0800.

**Comment by samir-syed** [comment]
Awesome! Thank you for your time and for making an awesome library.
