### ISSUE TITLE
ical.net 2.3.2 has a version conflict with NodaTime

### ISSUE THREAD

**Issue by AndreasESchneider** [ical-org/ical.net#301]
Seems that Ical.Net installs and references an old NodaTime.dll (1.3.1.0)

**Comment by rianjs** [comment]
Which version of ical.net are you using?

**Comment by AndreasESchneider** [comment]
Dear Rian, I am using iCal 2.3.2 from NuGet with .NET 4.5 and VS2015. After updating iCal from 2.2.34 NodaTime was referenced in the project from 2.0.3 to 1.3.1

**Comment by nicholashead** [comment]
Shouldn't nodatime be a package reference, not just bundled in?

**Comment by samcic** [comment]
I just installed ical.net 3.0.12 on a .net core project with NodaTime v2.1.0 already installed, and this worked as expected (i.e. ical.net is referencing the existing NodaTime nuget package in the project). So it looks like this may have been fixed by 3.0.12?

**Comment by rianjs** [comment]
I think this is resolved in the non-beta versions of v3+
