### ISSUE TITLE
Create an event with a reminder

### ISSUE THREAD

**Issue by FranzKiermaier** [ical-org/ical.net#308]
Hi, I am trying to create a reminder for an event, but wasn't able to find the properties to do that in the Event class.
Is it possible to add a reminder to an event?
Thanks for your help

**Comment by poulerik-dk** [comment]
Wouldn't this just be adding an alarm to the event?
ie.

    var reminder = new Alarm
    {
         Summary = "You have 15 minutes to be at that important meeting, you properly wont make it!",
         Action = AlarmAction.Display,
         Trigger = new Trigger(TimeSpan.FromMinutes(-15))
    };

    var calendarEvent = new Event
    {
        Alarms = { reminder }
    };

**Comment by FranzKiermaier** [comment]
Hi,
I’ve tried to add an alarm, but no success.
This is my code:

            foreach (var taskItem in taskItems.Where(t => t.DueDate != null && t.DueDate.HasValue == true))
            {
                var hyperlink = Request.GetBaseUrl();

                hyperlink = string.Format("{0}/TaskBoard/Tasks?listId={1}", hyperlink, taskItem.ListId);
                var dueDate = new DateTime(taskItem.DueDate.Value.Ticks, DateTimeKind.Utc);
                var alarm = new Alarm()
                {
                    Summary = taskItem.Title,
                    Trigger = new Trigger(TimeSpan.FromMinutes(-15)),
                    Action = AlarmAction.Display
                };

                var calendarEvent = new Event
                {
                    Class = "PUBLIC",
                    Summary = taskItem.Title,
                    Created = new CalDateTime(taskItem.Created.Value),
                    Description = string.Format("Open board: {0}", hyperlink),
                    Start = new CalDateTime(dueDate),
                    End = new CalDateTime(dueDate.AddDays(1)),
                    Uid = taskItem.Id.ToString(),
                    Location = taskItem.ListTitle
                    //IsAllDay = true
                };

                calendarEvent.Alarms.Add(alarm);
                calendar.Events.Add(calendarEvent);
            }

Mit freundlichen Grüßen / Kind regards,

Franz Kiermaier
Geschäftsführer
Certified SCRUM Master

[cid:FC6D9990-7A58-49A0-963D-B12A78C17FB9@fritz.box]
software creative GmbH
Franz-Böhm-Straße 2
94526 Metten

Telefon: +49 991 3209932
Mobil:     +49 175 2749174
Skype for business:       franz.kiermaier@software-creative.com<mailto:franz.kiermaier@software-creative.com>
www.software-creative.com<http://www.software-creative.com/>

software creative – Software & App Development – SCRUM – Microsoft Infrastructure – Cloud Solutions

software creative GmbH – Geschäftsführer: Franz Kiermaier – Sitz der Gesellschaft: Metten – Registergericht: AG Deggendorf HRB 3347 - USt-ID-Nr.: DE267238797

Die Information in dieser E-Mail ist vertraulich und ist ausschließlich fuer den Adressaten bestimmt. Jeglicher Zugriff auf diese eMail durch andere Personen als den Adressaten ist untersagt. Sollten Sie nicht der für diese eMail bestimmte Adressat sein, ist Ihnen jede Veröffentlichung, Vervielfältigung oder Weitergabe wie auch das Ergreifen oder Unterlassen von Maßnahmen im Vertrauen auf erlangte Information untersagt. In dieser E-Mail enthaltene Meinungen oder Empfehlungen unterliegen den Bedingungen des jeweiligen Kundenverhältnisses mit dem Adressaten.

Von: Poul Erik Venø [mailto:notifications@github.com]
Gesendet: Mittwoch, 23. August 2017 09:47
An: rianjs/ical.net <ical.net@noreply.github.com>
Cc: Franz Kiermaier <Franz.Kiermaier@software-creative.de>; Author <author@noreply.github.com>
Betreff: Re: [rianjs/ical.net] Create an event with a reminder (#308)


Wouldn't this just be adding an alarm to the event?
ie.
`var reminder = new Alarm
{
Summary = "You have 15 minutes to be at that important meeting, you properly wont make it!",
Action = AlarmAction.Display,
Trigger = new Trigger(TimeSpan.FromMinutes(-15))
};

        var calendarEvent = new Event

        {

            Alarms = { reminder }

        };`

**Comment by rianjs** [comment]
What is the behavior you're seeing? What is the behavior you expect to see? Re-open, or re-ask on StackOverflow.

**Comment by txwizard** [comment]
In lieu of comprehensive documentation generated by a tool, such as, for example, DocFX, I found this working example invaluable to get my freestanding ICAL generator working. I have yet to delve into the source to evaluate the feasibility of feeding it to DocFX or something similar. Since there is so much in this library, it would benefit greatly from such documentation.

**Comment by txwizard** [comment]
It bears noting as well that I have successfully integrated the library into an application that is currently in MVP stage, needing only a couple of changes to make it truly useful.
