### ISSUE TITLE
SerializeToString throw InvalidOperationException without PRODID

### ISSUE THREAD

**Issue by ewanzd** [ical-org/ical.net#311]
I programming a CalDAV server. There is a case, where it is conform to remove the PRODID and then serialize to string: [rfc4791 section-7.8.1](https://tools.ietf.org/html/rfc4791#section-7.8.1)
But `SerializeToString` of `CalendarSerializer` throw a `InvalidOperationException`.

I wrote a little function to show this case:

`var calendar = new Calendar();
calendar.ProductId = "-//MyProduct";
var prodId = calendar.Properties["PRODID"];
calendar.Properties.Remove(prodId);

var serializer = new CalendarSerializer(calendar);
var output = serializer.SerializeToString();`

**Comment by poulerik-dk** [comment]
@https://tools.ietf.org/html/rfc5545#section-3.7.3 says that this would not be a valid iCalendar object. 

If you want to produce an invalid iCalendar you could implement it as:

    var serializer = new ComponentSerializer();
    var output = serializer.SerializeToString(calendar);

**Comment by ewanzd** [comment]
Then do you assume rfc4791 section-7.8.1 is wrong? In a perspective the property is available in iCalendar object, but not included in the limited response.

Thanks for the code snippet

**Comment by poulerik-dk** [comment]
I don't know to be honest. But I see the point of not relaying PRODID, when only partial data is requested. Don't think of me as an authority on this matter though ;)

**Comment by rianjs** [comment]
[`PRODID` is a required property per the spec.](https://tools.ietf.org/html/rfc5545#section-3.7.3)
