### ISSUE TITLE
How to add System.Net.Mail.Attachment ContentId into Event Attachment

### ISSUE THREAD

**Issue by partharanjan** [ical-org/ical.net#313]
Hi,
Please help me to add System.Net.Mail.Attachment ContentId into Event Attachment

Example
ATTACH:CID:C60936638C0EFA47AB1DDB0F498C6A6C@eop-APC01.prod.protection.outlook.com
ATTACH:CID:EF67828D1FB93E4BBF418491B204F0E9@eop-APC01.prod.protection.outlook.com

Please check file
[file.txt](https://github.com/rianjs/ical.net/files/1279027/file.txt)

My issue is calendar is not showing in gmail when I have attachment in email.
Please help me

**Comment by rianjs** [comment]
Can you ask this question on StackOverflow, and paste the URL here? I prefer to answer questions there.
