### ISSUE TITLE
Recurring events with daylight savings time support [Question]

### ISSUE THREAD

**Issue by gjdownes** [ical-org/ical.net#314]
What's the best way to implement recurring dates which automatically adjust for DST? E.g an event should recur every day at 10am EST even when DST is in effect and should not jump backwards 1hr.

Currently I'm storing dates as UTC, but I also have access to the original timezone.

**Comment by rianjs** [comment]
Can you post the question on StackOverflow, and put the URL here? Those tend to have more visibility when people search with Google, and when I answer questions, I don't like to repeat myself. (I have a finite number of keystrokes before I die!) It's easier to reply with a URL to a StackOverflow post when one is available.

**Comment by gjdownes** [comment]
Absolutely! Here you go:
[https://stackoverflow.com/questions/46305614/recurring-events-with-daylight-savings-time-support-using-ical-net](https://stackoverflow.com/questions/46305614/recurring-events-with-daylight-savings-time-support-using-ical-net)

**Comment by rianjs** [comment]
https://stackoverflow.com/questions/46305614/recurring-events-with-daylight-savings-time-support-using-ical-net/46307259#46307259
