### ISSUE TITLE
Create an iCal.NET logo

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ical-org/ical.net#32]
Here are some options :). I prefer the first one.

![icalnet-heart](https://cloud.githubusercontent.com/assets/228256/16715493/2c6c8f04-46af-11e6-9b8d-92c5458e2b83.png)

![icalnet-grid](https://cloud.githubusercontent.com/assets/228256/16715495/2dcfe3f0-46af-11e6-83b2-b3f829373e80.png)

**Comment by rianjs** [comment]
I love it. (And I prefer the first one, too.)

Where/how do you think it should be used?

**Comment by khalidabuhakmeh** [comment]
I like to use them on the Readme as the header and any gh-pages documentation

**Comment by rianjs** [comment]
Sounds good. Do you want to add it to the readme?

**Comment by rianjs** [comment]
3b6c30896d8d338cbf99659709f8e8a76849cf56

**Comment by kdaveid** [comment]
I like it! You are working fast on this project. Following you commits!

Sorry, couldn't get back to you yet. Still busy with a customer project - but I switched to iCal.NET on that project so I guess I have to work with you on this to complete... ;-)
