### ISSUE TITLE
Nuget: Missing dependency: System.Reflection.TypeExtensions 4.3

### ISSUE THREAD

**Issue by medokin** [ical-org/ical.net#326]
The nuspec misses the System.Reflection.TypeExtensions 4.3 dependency.

**Comment by rianjs** [comment]
OK, I did a quick round-trip serialize-deserialize consuming v3 in a framework application. I think this is the last missing dependency. C.f. #324 from this morning.

https://www.nuget.org/packages/Ical.Net/3.0.15

(That link will work in a few minutes.)
