### ISSUE TITLE
CalDateTime.ToTimeZone produces UTC time instead of target time zone

### ISSUE THREAD

**Issue by pomoika** [ical-org/ical.net#330]
It looks like CalDateTime.ToTimeZone always creates CalDateTime in UTC even though internal conversion between source and destination time zones has been done properly (e.g. from "Central Standard Time" to "Eastern Standard Time"). The result is represented in UTC, whereas I would expect it in desired time zone. The same issue occurs in DateUtil.MatchTimeZone method.

**Comment by rianjs** [comment]
Could you provide a code example demonstrating the problem?

**Comment by pomoika** [comment]
Here is a simple sample:
```
            const string source = @"
BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
BEGIN:VEVENT
DTEND;TZID=Central Standard Time:20171102T093000
DTSTART;TZID=Central Standard Time:20171102T090000
RRULE:FREQ=WEEKLY;COUNT=4;BYDAY=MO
SEQUENCE:0
END:VEVENT
END:VCALENDAR";
            ICalendar cal = Calendar.LoadFromStream(new StringReader(source)).First();
            IDateTime start = cal.Events[0].Start;
            Console.WriteLine(start.ToString());
            IDateTime eastern = start.ToTimeZone("Eastern Standard Time");
            Console.WriteLine(eastern.ToString());
```
11/2/2017 9:00:00 Central Standard Time
11/2/2017 14:00:00 UTC

**Comment by rianjs** [comment]
Fixed in nuget version 4.0.0: https://www.nuget.org/packages/Ical.Net/4.0.0

**Comment by afterlogic-support** [comment]
Those who are not on .NET Core are out of luck to get this fix?

**Comment by rianjs** [comment]
v4 is .NetStandard 1.3, which means you can use it with .NET 4.6 and higher.

**Comment by afterlogic-support** [comment]
My target is .NET 4.5. Anyway, I took the fixed code from net-core branch and made it work as a separate util method (so I'm not using ToTimeZone at all now). Can live with that for now. Thanks!

**Comment by rianjs** [comment]
In a perfect world, I would support .NET 4.5+, but there were reasons (that I can't recall now) why .NetStandard < 1.3 wouldn't work.
