### ISSUE TITLE
mail app in windows not showing proper end date

### ISSUE THREAD

**Issue by zoinkydoink** [ical-org/ical.net#334]
I have the following .ics file, and always keep my raw dates in UTC so I think the right way put dates into `CalendarEvent` is ` DtStart = new CalDateTime(ev.StartDateTimeUTC, "Utc")`

     BEGIN:VCALENDAR
     PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.0//EN
     VERSION:2.0
     BEGIN:VEVENT
     DESCRIPTION:Blockchain for Wall Street is an annual event from the Wall St
         reet Blockchain Alliance\, presented for its membership and as a service 
         to the broader industry. The WSBA is a neutral\, unbiased steward of educ
        ation and cooperation between Wall Street firms with a membership that is
        comprised of some of the most influential and seasoned technologists in 
        the blockchain and distributed ledger community.
     DTEND:20171115T045900Z
     DTSTAMP:20171113T231608Z
     DTSTART:20171114T140000Z
     SEQUENCE:0
     SUMMARY:Blockchain For Wall Street
     UID:7aa68f0e-adc5-4af2-80b9-429ef1f5f193
     END:VEVENT
     END:VCALENDAR

which is generated by 

       public IActionResult DownloadICS(int id)
        {
            var ev = DbContext.CryptoEvents.Find(id);
            var e = new CalendarEvent
            {
                DtStart = new CalDateTime(ev.StartDateTimeUTC, "Utc"),
                DtEnd = new CalDateTime(ev.EndDateTimeUTC, "Utc"),
                Summary = ev.Title,
                Description = ev.Summary
            };

            var calendar = new Calendar();
            calendar.Events.Add(e);
            var serializer = new CalendarSerializer(new SerializationContext());
            var serializedCalendar = serializer.SerializeToString(calendar);
            var bytes = Encoding.UTF8.GetBytes(serializedCalendar);
            var contentType = "text/calendar";
            return File(bytes, contentType, $"CRYPTOCAL_EVENT_{id}.ics");
        }

The above time start time should be `9:00 AM Eastern Standard` and `11:59 PM Eastern Standard`.
My Windows 10 machine is set to Eastern Time standard, so I expect when i import this file it should show the `9:00 am` and `11:59 pm` but instead it shows `9:00 am` for start and `6:30pm` for end

I just upgraded to v4.0 and had to make some adjustments to my code for it to work such as changing the namespace where CalendarEvent lives (by the way not sure why all the docs say the class is Event instead of CalendarEvent).

I also had remove `Name = Components.Event` as a property set on the `CalendarEvent` because apparently that is no longer supported/available in v4.0

It seems there is a bit of disconnect between the documentation/samples provided and the actual code in nuget.

**Comment by rianjs** [comment]
You're importing UTC times (`Z` suffix on your `DTSTART` and `DTEND`). If you want to convert the UTC times to local time, you need to call `ToTimeZone()`. Example:

```csharp
[Test]
public void StartEndTimes()
{
    const string ics = @"BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.0//EN
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION:Blockchain for Wall Street is an annual event from the Wall St
    reet Blockchain Alliance\, presented for its membership and as a service 
    to the broader industry. The WSBA is a neutral\, unbiased steward of educ
   ation and cooperation between Wall Street firms with a membership that is
   comprised of some of the most influential and seasoned technologists in 
   the blockchain and distributed ledger community.
DTEND:20171115T045900Z
DTSTAMP:20171113T231608Z
DTSTART:20171114T140000Z
SEQUENCE:0
SUMMARY:Blockchain For Wall Street
UID:7aa68f0e-adc5-4af2-80b9-429ef1f5f193
END:VEVENT
END:VCALENDAR";

    var firstEvent = Calendar.Load(ics).Events.Single();
    Assert.AreEqual(new CalDateTime(DateTime.Parse("2017-11-14 14:00:00"), "UTC"), firstEvent.Start);
    Assert.AreEqual(new CalDateTime(DateTime.Parse("2017-11-15 04:59:00"), "UTC"), firstEvent.End);

    const string targetTimeZone = "Eastern Standard Time";
    var localStart = firstEvent.Start.ToTimeZone(targetTimeZone);
    var localEnd = firstEvent.End.ToTimeZone(targetTimeZone);

    Assert.AreEqual(new CalDateTime(DateTime.Parse("2017-11-14 09:00:00"), targetTimeZone), localStart);
    Assert.AreEqual(new CalDateTime(DateTime.Parse("2017-11-14 23:59:00"), targetTimeZone), localEnd);
}
```

> I also had remove Name = Components.Event as a property set on the CalendarEvent because apparently that is no longer supported/available in v4.0

That happens automatically during construction; there's no need to do it manually.

> I just upgraded to v4.0 and had to make some adjustments to my code for it to work such as changing the namespace where CalendarEvent lives (by the way not sure why all the docs say the class is Event instead of CalendarEvent).

The documentation largely targets v2. You're right, though, it does need to be updated for v3+.
