### ISSUE TITLE
Shouldn't the VERSION property have a value of 2.0 (not 4.0)?

### ISSUE THREAD

**Issue by samcic** [ical-org/ical.net#344]
RFC 5545 notes about the VERSION property of the CALENDAR object:

> A value of "2.0" corresponds to this memo.

In ical.net version 4.0.4, the following simple serialization of a Calendar gives VERSION=4.0

```
            var calendar = new Calendar();
            var ctx = new SerializationContext();
            var factory = new SerializerFactory();
            var serializer = factory.Build(calendar.GetType(), ctx) as IStringSerializer;
            var result = serializer.SerializeToString(calendar);
```

I'd like to propose that this is a bug. Namely, it causes issues on Apple devices (i.e. Apple devices will choke even on an empty calendar if VERSION=4.0).

**Comment by rianjs** [comment]
Yes, you're quite right.

**Comment by rianjs** [comment]
Fixed in 4.0.5:

https://www.nuget.org/packages/Ical.Net/4.0.5

**Comment by samcic** [comment]
Thanks for the quick fix! I did however notice that the PRODID has now also been updated. Was that intentional? It now serializes as:

`PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.0//EN`

Presumably you didn't want to change this one as well? :)

**Comment by rianjs** [comment]
[Nope](https://tools.ietf.org/html/rfc5545#section-3.7.3). :)

> 3.7.3.  Product Identifier
> 
>    Property Name:  PRODID
> 
>    **Purpose:  This property specifies the identifier for the product that
>       created the iCalendar object.**
> 
>    Value Type:  TEXT
> 
>    Property Parameters:  IANA and non-standard property parameters can
>       be specified on this property.
> 
>    Conformance:  The property MUST be specified once in an iCalendar
>       object.
> 
>    Description:  The vendor of the implementation SHOULD assure that
>       this is a globally unique identifier; using some technique such as
>       an FPI value, as defined in [ISO.9070.1991].
> 
>       This property SHOULD NOT be used to alter the interpretation of an
>       iCalendar object beyond the semantics specified in this memo.  For
>       example, it is not to be used to further the understanding of non-
>       standard properties.
> 
>    Format Definition:  This property is defined by the following
>       notation:
> 
>        prodid     = "PRODID" pidparam ":" pidvalue CRLF
> 
>        pidparam   = *(";" other-param)
> 
>        pidvalue   = text
>        ;Any text that describes the product and version
>        ;and that is generally assured of being unique.
> 
>    Example:  The following is an example of this property.  It does not
>       imply that English is the default language.
> 
>        PRODID:-//ABC Corporation//NONSGML My Product//EN
>

**Comment by samcic** [comment]
I'm not sure if by "nope" you mean that you *did* intend to change the PRODID value, but I can't see anything in the spec that says you must have a "2.0" in it.

Indeed, it mentions it "should" contain a value that *describes the product and version and that is generally assured of being unique*.

The "product version" in this case would be 4.0.5, wouldn't it? In my opinion, it would be useful when looking at a serialized Calendar to know which version of ical.net was responsible (potentially useful for issue-reproduction and debugging). This seems to be the motivation behind the PRODID property if I understand correctly.

**Comment by rianjs** [comment]
Ugh, I was too clever with encoding the PRODID version. Originally I had thought that VERSION meant something about the library, similar to PRODID. That was why I had linked them.

Then you pointed out that VERSION should be 2.0, so I changed it without looking at any other lines. Brilliant. :1st_place_medal: 

Anyway, my intent was for PRODID to stay at 4.0, and VERSION to go back to 2.0

**Comment by samcic** [comment]
👍

**Comment by rianjs** [comment]
https://www.nuget.org/packages/Ical.Net/4.0.6
