### ISSUE TITLE
calendar deserialize failed because of blanks

### ISSUE THREAD

**Issue by HolzetheKid** [ical-org/ical.net#347]
Hallo, 
the following calendar string fails with exception message 
_System.Runtime.Serialization.SerializationException: 'Expected 'END: VCALENDAR', found 'END:VCALENDAR''_

--> do you see that he is expecting a blank( " ")  after the ":" ? why ?

using current version:

```
using Ical.Net;
using Ical.Net.Serialization;
using System.IO;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {

            string calendarstr ="BEGIN: VCALENDAR\r\nVERSION: 2.0\r\nPRODID: -//MailClient.VObject/7.1.30794.0\r\nMETHOD:REQUEST\r\nBEGIN:VTIMEZONE\r\nTZID:W. Europe Standard Time\r\nX-EM-DISPLAYNAME:(UTC+01:00) Amsterdam\\, Berlin\\, Bern\\, Rom\\, Stockholm\\, \r\n Wien\r\nBEGIN:STANDARD\r\nTZNAME:Mitteleuropäische Zeit\r\nDTSTART:00010101T030000\r\nTZOFFSETFROM:+0200\r\nTZOFFSETTO:+0100\r\nRRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10\r\nEND:STANDARD\r\nBEGIN:DAYLIGHT\r\nTZNAME:Mitteleuropäische Sommerzeit\r\nDTSTART:00010101T020000\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0200\r\nRRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3\r\nEND:DAYLIGHT\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nUID:99ca3cae-227a-424c-8d97-7b11d7c7aae9\r\nSEQUENCE:1\r\nDTSTART;TZID=W. Europe Standard Time:20171130T080000\r\nDTEND;TZID=W. Europe Standard Time:20171130T083000\r\nTRANSP:OPAQUE\r\nX-MICROSOFT-CDO-BUSYSTATUS:BUSY\r\nLAST-MODIFIED:20171127T210957Z\r\nDTSTAMP:20171127T210955Z\r\nCREATED:20171127T210955Z\r\nSUMMARY:rsponse test\r\nDESCRIPTION:response test\r\nLOCATION:dsfgj\r\nATTENDEE;CN=xxxxx@freenet.de;RSVP=TRUE:mailto:xxxxx@freen\r\n et.de\r\nORGANIZER;CN=xxxx xxxxx:mailto:xxxxxx@gmx.de\r\nCLASS:PUBLIC\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n\r\n";
                      
            var iCal = Calendar.Load(calendarstr);
        }
    }
}

```

**Comment by rianjs** [comment]
It’s probably expecting the tokens to match exactly. Your BEGIN token has a space (‘BEGIN: VCALENDAR’) but the end doesn’t match. 

The right thing to do would be throw a SerializationException in the event of an invalid space like you have on the first line.

**Comment by HolzetheKid** [comment]
ok, so i need to verify if the string i good before parsing.  

 thanks for the information

**Comment by rianjs** [comment]
Reopening because this should fail to parse the first token, so it’s a bug.

**Comment by axunonb** [comment]
END: VCALENDAR with a blank space after END: is not a valid entry in an ICS file. According to the iCalendar (ICS) specification (RFC 5545), the END property should not have any spaces between END: and the component name. The correct format should be END:VCALENDAR. The same applies for other properties.
We don't see a point to making parsing more fault tolerant.
