### ISSUE TITLE
Filter Occurrences

### ISSUE THREAD

**Issue by M2xAy** [ical-org/ical.net#350]
Hi Rian Hi Douglas,
thank you for this ncie Library.

I have some Problem with filter occurrences.

My Events Begins at 05.12.2017 end ending at 11.03.2018

I will filter and Show only the Events beetween 05.01.2018 and 31.12.2019

I use  for test:

`foreach (CalendarEvent e in vEventListe)
                    {
                        calendar.Events.Add(e);
                        var test = e.GetOccurrences(searchStart, searchEnd);
                    }
                    occurrences = calendar.GetOccurrences(searchStart, searchEnd);`

the result is Events from 05.12.2017 to 11.03.2018

is the method false for filtering? or is this a bug ? 

Best regards

**Comment by ignite-404** [comment]
i think the filter is like events.where(x=x.has_inner_section_with(start,end))
@M2xAy

**Comment by M2xAy** [comment]
Hi Hiwjcn,
thank you for your answer.

It works also with getoccurencses, my Events was false in db.

Sorry

you can Close the issue.

Best regards
