### ISSUE TITLE
Having issue in TFS build with symbols not found...

### ISSUE THREAD

**Issue by benjamin-goldman** [ical-org/ical.net#351]
Hi - we have a solution build on TFS that is failing due to Ical.Net.pdb missing during a build:

##[error]Indexed source information could not be retrieved from '......\Ical.Net.pdb'. Symbol indexes could not be retrieved.

I am seeing some possible items out on the internet that might lead toward a solution - but I was wondering if this is possibly due to an incorrect Nuget publish?

**Comment by nikk1e** [comment]
+1 Same issue here

**Comment by rianjs** [comment]
What nuget version? All versions should include the PDB in the nuget package.
