### ISSUE TITLE
NullReferenceException when serializing IICalendarCollection

### ISSUE THREAD

**Issue by afterlogic-support** [ical-org/ical.net#352]
var calendar = Calendar.LoadFromStream(sr);
    var serializer = new CalendarSerializer();
    var serializedCalendar = serializer.SerializeToString(calendar);

This code crashes with NullReferenceException. It does not seem to be obvious that the parser outputs  CalendarCollection (IICalendarCollection, to be precise) while the builder deals with single ICalendar instances only. I.e. the parser and the builder are not consistent.

SerializeToString signature is like this:

    public override string SerializeToString(object obj); 

This makes the reader (me) think that it should accept any type of calendar-like object, be it a single calendar or a collection. Especially, a collection, as it's the object that the parser produces (for object model consistency purposes). Nevertheless, it should not crash with NullReferenceException anyway.

**Comment by rianjs** [comment]
Which nuget version?

**Comment by Derpeta** [comment]
Same issue:

`[31-12-2017 17:31:34] [Error] [Client] Ical.Net : KaasAsync : Object reference not set to an instance of an object.
   at Ical.Net.Serialization.CalendarSerializer.SerializeToString(Object obj) in FilePath\CalendarSerializer.cs:line 31
   at wupwup`

version: 4.0.6

**Comment by afterlogic-support** [comment]
I wasn't using nuget, I downloaded the latest version directly from github (earlier today).

**Comment by rianjs** [comment]
Did you install [the dependencies](https://github.com/rianjs/ical.net/blob/master/net-core/Ical.Net.nuspec#L16)?

**Comment by Derpeta** [comment]
lol derp, Visual studio did not install NodaTime automatically. Works for me now. Thanks.

**Comment by rianjs** [comment]
👍

**Comment by afterlogic-support** [comment]
I don't get it why this thread was closed as the issue is still not resolved. Yes, NodaTime was installed right from the start. So is System.Runtime.Serialization.Primitives and others. Anyway, it has nothing to do with dependencies (at least from what I see):

        public override string SerializeToString(object obj)
        {
            var iCal = obj as ICalendar;

            // Ensure VERSION and PRODUCTID are both set,
            // as they are required by RFC5545.
            if (string.IsNullOrWhiteSpace(iCal.Version))
            {
                iCal.Version = CalendarVersions.Latest;
            }
            if (string.IsNullOrWhiteSpace(iCal.ProductId))
            {
                iCal.ProductId = CalendarProductIDs.Default;
            }

            return base.SerializeToString(iCal);
        }

As obj is not ICalendar instance (it's IICalendarCollection), this results in iCal being null so that iCal.Version cannot be resolved. How can dependencies be related?

**Comment by rianjs** [comment]
Oh I see. Derpeta borrowed your thread.
