### ISSUE TITLE
Can't compile project after adding ical.net

### ISSUE THREAD

**Issue by allesBuchen** [ical-org/ical.net#353]
I guess it's just a small thing, but i don't get it...
I've got an asp.net web api project targeting framework 4.6.1. Everything works fine.
After adding ical.net 4.0.6 via NuGet i'm getting the following error during compilation of the project:

BC32210	Multiple assemblies with equivalent identity have been imported: 'C:\Develop\project_folder\packages\System.Runtime.Serialization.Primitives.4.3.0\lib\net46\System.Runtime.Serialization.Primitives.dll' and 'C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.Runtime.Serialization.Primitives.dll'. Remove one of the duplicate references.

First one seems to have Version 4.1.2.0 and second one 4.0.10.0.

I've already implemented a binding redirect for the assembly
(oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0"), but it will not compile correctly.

What am i doing wrong?? 

Thanx in advance for help or a hint.

Henner

**Comment by rianjs** [comment]
Yeah, this is an issue with mixing .NetStandard libraries with .NET Framework code that Microsoft is working on. Have a look here: https://github.com/dotnet/standard/issues/481
