### ISSUE TITLE
Regroup several calendars in one

### ISSUE THREAD

**Issue by Mortaurat** [ical-org/ical.net#354]
Hello everyone,
I'm trying to master the Ical.net library, but i got some issues regarding one point.
I have an object called Property, which has an ical.net.Calendar attribute called calendar.
My object property has one method called Update_Calendar, which find some URL on the database, download it and read it.
Each URL containts one calendar, and in want to regroup all this calendars into one (which is called calendar).

This code in my opinion should works, but i got an issue in the line : calendar.Events.Add(e);

Could you please explain me why, and if there is an easier solution to do what i want to do ?

Regards

      public void Update_Calendar()
        {
            var Temp = new Ical.Net.Calendar();
            var e = new CalendarEvent();
            int i = 0;
            int j = 0;
            string icalText; 
            while (i < 5)
            {
                if (Property_channel_URL[i] != "")
                {
                    // try
                    //{
                    DownloadICS(Property_channel_URL[i], Property_Owner + Property_Name + Property_channel_Name[i] + ".ics");
                    icalText = System.IO.File.ReadAllText(@"C:\Path\" + Property_Owner + Property_Name + Property_channel_Name[i] + ".ics");
                    Temp = Ical.Net.Calendar.Load(icalText);
                    while (j < Temp.Events.Count)
                    {
                        e = Temp.Events.ElementAt(j);
                        calendar.Events.Add(e);
                        j++;
                    }
                    j = 0;
                }
                    // catch { }
                }
                    i++;            
        }

**Comment by rianjs** [comment]
This is a general C# programming question, and better suited to a place like StackOverflow.
