### ISSUE TITLE
Documentation request: required .net framework

### ISSUE THREAD

**Issue by jdoose** [ical-org/ical.net#357]
I wanted to add ical.net to my project and it was not easy, because it wasn't clear, what the required minimum framework version was. I started with 4.0, then 4.5.x and ended with 4.6, which finally worked.
This is due to dependencies: NodaTime is not supported with 4.0, System.Reflection.TypeExtensions requires min. 4.6

A big help would be to add the required .net framework versions to the documentation

**Comment by rianjs** [comment]
Good idea. 

In the meantime, v2 works with earlier versions of .NET. I think as low as 4. 

V3+ is .NetStandard 1.3+
