### ISSUE TITLE
Why does ical does not include DateTimeOffset for calendar events

### ISSUE THREAD

**Issue by rohit-gh** [ical-org/ical.net#361]
There is way too much manipulation for DateTimeOffset to datetime conversions , offsets  and timezone.
why not come up with simeple plan

**Comment by rianjs** [comment]
You'll have to be more specific with your complaint.

https://stackoverflow.com/help/how-to-ask

**Comment by M0ns1gn0r** [comment]
https://stackoverflow.com/help/how-to-answer
