### ISSUE TITLE
Strong sign assemblies

### ISSUE THREAD

**Issue by yokensei** [ical-org/ical.net#362]
Hello.
In my project, I sign the assembly. An assembly error occurred when I refer to Ical.Net.
Could you sign the assembly?

**Comment by rianjs** [comment]
Why are you strong-signing your assemblies?

**Comment by yokensei** [comment]
It is because strong-signing is an important rule in my project.

**Comment by dolunay** [comment]
Could you sign the assembly? Very important reason for using framework based projects.
