### ISSUE TITLE
Get events occurring right now

### ISSUE THREAD

**Issue by karlromanowski** [ical-org/ical.net#363]
calendarFile.GetOccurrences(DateTime.UtcNow, DateTime.UtcNow) used to just return the events that were happening right now, but after updating to the latest version this is no longer the case. Was this an intentional change, or is there another way of getting events in progress apart from checking Start/End dates explicitly?

**Comment by rianjs** [comment]
Before the most recent version(s), all occurrences were computed in terms of UTC. Now local times are first-class entities for computing recurrence sets. I think this should give you the equivalent:

```charp
var now = new CalDateTime(DateTime.Now, "yourLocalTimeZone");
var happeningNow = calendar.GetOccurrences(now, now);
```
