### ISSUE TITLE
work meeting once a month

### ISSUE THREAD

**Issue by orih2808** [ical-org/ical.net#367]
Can i create an event every month, but if in a specific month the month day is  Saturday move it in a day?
Thanks

**Comment by minichma** [comment]
Google is your friend for questions like this. That said, you could try something like `FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR,SU;BYSETPOS=1;BYMONTHDAY=15,16`. This yields every 15th of a month, except if it's a saturday, in which case it yields the 16th. However, this will only work reliably if the month day < 28.
