### ISSUE TITLE
Invalid NZDST RRUles post 2009

### ISSUE THREAD

**Issue by cdmdotnet** [ical-org/ical.net#369]
I'm tracking an odd bug. Currently (2017) NZ is in DST. Using NodaTime DB 'TZDB: 2018c (mapping: 13290)' ICal.NET returns an incorrect NZDST offset. It calculates UTC+11, rather than UCT+13. I suspect the issue here is that testing is done with timezones that are ST when a new year starts and not DST when a new year starts I.E. the magic problem here might be the assumption of January the first as the default earlistDateTimeToSupport... Northern hemisphere testing only. Anyways...

Walking through `public static VTimeZone FromTzId(string tzId)` using "Pacific/Auckland" as the tzId, the methods calculate the earliest date to query as 2017-1-1... fine so far (maybe for northern hemisphere timezones... maybe not for southern hemisphere timezones). It finds the intervals from 2017-1-1 until now...There are three, one DST, One ST and a final DST (the current one).
Moving on the latestDaylightInterval is correctly identified and then `var latestDaylightTimeZoneInfo = CreateTimeZoneInfo(matchingDaylightIntervals, intervals);` is called. Here things get weird.

The `oldestInterval` is matched as the first interval in the set of DST known intervals, and then `previousInterval` is looked for. This will ALWAYS return null, as the `oldestInterval` is the first. If this was a northen hemisphere timezone then obviously there would be an ST timezone still in that set to find it's previous timezone.

Anyways, things move on with a default delta of +1 hour, and finally we get to `timeZoneInfo.OffsetTo = new UtcOffset(utcOffset - delta);`. This seems very odd. with a default of +1 hour the delta is calculated in the reverse direction, taking an hour off, not adding one.

Anyways I've got no concrete ideas but could suggest the following change. It's a change with the smallest footprint. I have no idea about it's collateral damage to assumptions made later in the code, but it atleast got me the correct timezones for southern hemisphere timezones... not sure what it will do for northern hemisphere timezones. The main change is checking if the first DST is the first tz in the whole set... if so, walk back one more and find an ST... I have no idea what impact this will have of dates prior to recent years... like those without previous STs. The whole try/catch block could be removed if you check if `firstDstInterval.Start` can go back further in time.

```csharp
// check to see if there is no active, future daylight savings (ie, America/Phoenix)
if(latestStandardInterval != null && latestStandardInterval.End != Instant.MaxValue)
{
    //daylight
    var daylightIntervals = intervals.Where(x => x.Savings.ToTimeSpan() != new TimeSpan(0)).ToList();

    if (daylightIntervals.Any())
    {
        var latestDaylightInterval = daylightIntervals.OrderByDescending(x => x.Start).FirstOrDefault();
        matchingDaylightIntervals = GetMatchingIntervals(daylightIntervals, latestDaylightInterval, true);
        var dstIntervals = intervals;
        var firstDstInterval = intervals.OrderBy(x => x.Start).First();
        if (daylightIntervals.OrderBy(x => x.Start).First() == firstDstInterval)
        {
            try
            {
                dstIntervals = zone.GetZoneIntervals(firstDstInterval.Start.Minus(Duration.FromHours(1)), SystemClock.Instance.Now).Where(x => x.Start != Instant.MinValue).ToList();
            }
            catch { }
        }
        var latestDaylightTimeZoneInfo = CreateTimeZoneInfo(matchingDaylightIntervals, dstIntervals);
        vTimeZone.AddChild(latestDaylightTimeZoneInfo);
    }
}

**Comment by rianjs** [comment]
I think you've started your ticket in the middle of a thought. :) Can you provide a small code example (using ical) that fails? Ideally I'd like to see some code with an explanation of

1. What happens
2. What you expected to happen instead

Your version of ical.net would also be helpful. The tzdata underlying NodaTime is different between v2 and v3+.

For example, I just did this, and it had a +13:00 offset:

```csharp
const string tzId = "Pacific/Auckland";
var zone = DateTimeZoneProviders.Tzdb[tzId];
var start = new CalDateTime(DateTime.Parse("2017-12-20 01:00:00"), tzId);
var end = start.AddHours(1);

var recurrenceRule = new RecurrencePattern(FrequencyType.Daily, 1)
{
    Until = DateTime.Parse("2018-07-31")
};

var e = new CalendarEvent
{
    DtStart = start,
    DtEnd = end,
    RecurrenceRules = new List<RecurrencePattern> { recurrenceRule },
};

var searchStart = DateTime.Parse("2017-12-25");
var searchEnd = DateTime.Parse("2018-01-05");
var occurrences = e.GetOccurrences(searchStart, searchEnd);

foreach (var o in occurrences)
{
    Debug.WriteLine($"Local: {o.Period.StartTime}");

    // Maybe ToDateTimeOffset() should be a method on IDateTime...
    var asOffset = LocalDateTime.FromDateTime(o.Period.StartTime.Value).InZoneLeniently(zone).ToDateTimeOffset();
    Debug.WriteLine($"\tAs DTOffset: {asOffset}");
}
```

Output:
```
Local: 12/25/2017 1:00:00 AM Pacific/Auckland
	As DTOffset: 12/25/2017 1:00:00 AM +13:00
Local: 12/26/2017 1:00:00 AM Pacific/Auckland
	As DTOffset: 12/26/2017 1:00:00 AM +13:00
Local: 12/27/2017 1:00:00 AM Pacific/Auckland
	As DTOffset: 12/27/2017 1:00:00 AM +13:00
Local: 12/28/2017 1:00:00 AM Pacific/Auckland
	As DTOffset: 12/28/2017 1:00:00 AM +13:00
Local: 12/29/2017 1:00:00 AM Pacific/Auckland
	As DTOffset: 12/29/2017 1:00:00 AM +13:00
Local: 12/30/2017 1:00:00 AM Pacific/Auckland
	As DTOffset: 12/30/2017 1:00:00 AM +13:00
Local: 12/31/2017 1:00:00 AM Pacific/Auckland
	As DTOffset: 12/31/2017 1:00:00 AM +13:00
Local: 1/1/2018 1:00:00 AM Pacific/Auckland
	As DTOffset: 1/1/2018 1:00:00 AM +13:00
Local: 1/2/2018 1:00:00 AM Pacific/Auckland
	As DTOffset: 1/2/2018 1:00:00 AM +13:00
Local: 1/3/2018 1:00:00 AM Pacific/Auckland
	As DTOffset: 1/3/2018 1:00:00 AM +13:00
Local: 1/4/2018 1:00:00 AM Pacific/Auckland
	As DTOffset: 1/4/2018 1:00:00 AM +13:00
```

**Comment by cdmdotnet** [comment]
Sure.
`VTimeZone itz = VTimeZone .FromTzId("Pacific/Auckland" );`

That's all you need to do to get an invalid Timezone. Nothing else. Just that. In a use case... very bare and totally stripped down to see the fault...

	VTimeZone itz = VTimeZone.FromTzId("Pacific/Auckland" );
	var iCal = new Calendar();
	iCal.AddTimeZone(itz);
	var serializer = new CalendarSerializer(iCal);
	string iCalData = serializer.SerializeToString(iCal);


The DST timezone information will be UTC+11

> BEGIN:VCALENDAR
> PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
> VERSION:2.0
> BEGIN:VTIMEZONE
> TZID:Pacific/Auckland
> X-LIC-LOCATION:Pacific/Auckland
> BEGIN:STANDARD
> DTSTART:20170402T030000
> RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=4
> TZNAME:NZST
> TZOFFSETFROM:+1300
> TZOFFSETTO:+1200
> END:STANDARD
> BEGIN:DAYLIGHT
> DTSTART:20160925T040000
> RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=9
> TZNAME:NZDT
> TZOFFSETFROM:+1200
> TZOFFSETTO:+1100
> END:DAYLIGHT
> END:VTIMEZONE
> END:VCALENDAR


With my suggested/potential change above (as I said no assurances it does much more than a hack at my specific issue) I get UTC+13:

> BEGIN:VCALENDAR
> PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
> VERSION:2.0
> BEGIN:VTIMEZONE
> TZID:New Zealand Standard Time
> X-LIC-LOCATION:New Zealand Standard Time
> BEGIN:STANDARD
> DTSTART:20170402T030000
> RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=4
> TZNAME:New Zealand Standard Time
> TZOFFSETFROM:+1300
> TZOFFSETTO:+1200
> END:STANDARD
> BEGIN:DAYLIGHT
> DTSTART:20160925T020000
> RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=9
> TZNAME:New Zealand Summer Time
> TZOFFSETFROM:+1200
> TZOFFSETTO:+1300
> END:DAYLIGHT
> END:VTIMEZONE
> END:VCALENDAR
