### ISSUE TITLE
v3 suggestion - more consistent valid property values

### ISSUE THREAD

**Issue by mcshaz** [ical-org/ical.net#37]
I am not hugely familiar with the library, and I may have missed important features of the library in which case I apologise. Assigning values to properties with a limited number of valid values under the spec seems inconsistent.

The Event property Class is a string, and the developer must know (or look up) valid values are "PUBLIC" or "PRIVATE", the same for an Attendee property Role (e.g. "REQ-PARTICIPANT").

the Event properties Transparency and Status are Enums.

An Attendee ParticipationStatus string property can be assigned from the const strings in the ParticipationStatus namespace. The same applies to the Calendar Method property and the CalendarMethods namespace

It would seem ideal if the above 6 properties all had a similar method of asignment.

Thanks

**Comment by rianjs** [comment]
Moved here: https://github.com/rianjs/ical.net/issues/24#issuecomment-232540224
