### ISSUE TITLE
Preventing clashing events

### ISSUE THREAD

**Issue by Aardvark02** [ical-org/ical.net#375]
I've never used RFC5545 calendars or iCal.net before. My question is very simple: how do I prevent clashing events when adding them to a calendar? If I add an event to a calendar, with opaque transparency, and then attempt to add another event that is the same except if has a different UID (i.e. same dates, same attendee) I'd expected iCal.net to raise an exception or otherwise prevent the clashing event from being added, but it just adds the second event without complaint. I'm obviously missing something fundamental here, but any assistance for a newbie would be welcome.

Serialised version of calendar after adding second event is:

BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
BEGIN:VEVENT
ATTENDEE;PARTSTAT=ACCEPTED:urn:party:f193d4c5-f292-4335-ad39-0e2f08
 58ea7e
ATTENDEE;PARTSTAT=TENTATIVE:urn:party:0a16cb91-e8e8-4e33-a7d6-42a7d
 ccbc714
CATEGORIES:Appointment
DTEND;VALUE=DATE:20180506
DTSTAMP:20180410T143758Z
DTSTART;VALUE=DATE:20180504
ORGANIZER:urn:party:f193d4c5-f292-4335-ad39-0e2f0858ea7e
SEQUENCE:0
STATUS:Confirmed
TRANSP:Opaque
UID:ad619947-9800-4b4e-bdf5-7a810916d3fc
END:VEVENT
BEGIN:VEVENT
ATTENDEE;PARTSTAT=ACCEPTED:urn:party:0a16cb91-e8e8-4e33-a7d6-42a7dc
 cbc714
CATEGORIES:Appointment
DTEND;VALUE=DATE:20180506
DTSTAMP:20180410T143758Z
DTSTART;VALUE=DATE:20180504
ORGANIZER:urn:party:f193d4c5-f292-4335-ad39-0e2f0858ea7e
SEQUENCE:0
STATUS:Confirmed
TRANSP:Opaque
UID:b3b9694d-6459-4d44-a1f4-acdb1a7c1bac
END:VEVENT
END:VCALENDAR

**Comment by rianjs** [comment]
>  how do I prevent clashing events when adding them to a calendar? If I add an event to a calendar, with opaque transparency, and then attempt to add another event that is the same except if has a different UID (i.e. same dates, same attendee) I'd expected iCal.net to raise an exception or otherwise prevent the clashing event from being added, but it just adds the second event without complaint.

Why would you expect duplicates to `throw`? What does duplicate even mean? This is more than a pedantic concern:
- Are events with the same attendees but different locations the same event?
- What about two events that are the same, except one has recurrence rules, but one doesn't?
- What about events that are identical in every way, except one has an attachment and one doesn't?

What should the behavior be in these cases?

"The same" is a concept best left to your application. To that end, `Calendar.Events` is a `List`, not an `ISet`. If you want to deduplicate events, you can do something like:

```csharp
var orderedUniques = myCalendar.Events
    .Distinct()
    .OrderBy(e => e.Start)
    .ToList();

myCalendar.Events = orderedUniques;
```

This is a very strict comparison: resources, attendees, start, end, time zones, EXDATEs, RRULEs, the bytes of an attachment, etc. are all considered; if it's not a 100% match, they aren't the same. That may be too strict for your use case. Or that might be OK; it's up to you to decide.

**Comment by Aardvark02** [comment]
Wow thanks for the very quick response! It looks like I wasn't clear at all. What I was trying to say was... If I add an event to a calendar, and that event blocks out some time as busy for a given attendee, then I wouldn't expect  to be able to add another (blocking) event at the same time for that same attendee. Is it the case that before I add an event my app needs to do a FreeBusy check to see if the slot is available for that attendee, rather than expect the calendar object to reject the second event?

**Comment by rianjs** [comment]
> If I add an event to a calendar, and that event blocks out some time as busy for a given attendee, then I wouldn't expect to be able to add another (blocking) event at the same time for that same attendee. 

Why? I can have multiple overlapping Busy events in Outlook and Google Calendar. What if my attendee is a bot that can be in two places at once?

“Not allowed”, like “the same”, is an application concern.

**Comment by Aardvark02** [comment]
Thanks Rian, that's perfectly clear now, and what you say makes complete sense. As I said, calendar software is very new to me. I wasn't aware that other services like Outlook and Google allowed overlapping Busy events. I certainly didn't mean my newbie question to be critical of iCal.Net in any way. I'll close this issue, and thanks once again both for providing the iCal.Net component and such great support.
