### ISSUE TITLE
Does iCal.Net 4.0.6 support .NET Framework 4.7.1?

### ISSUE THREAD

**Issue by KwalityKoder** [ical-org/ical.net#377]
After upgrading my ASP .Net application to 4.7.1 from 4.6.2, I keep getting runtime errors due to unable to find System.Runtime.Serialization.Primitive when Calendar.Load() is called. See below.
As part of 4.7.1, System.Runtime.Serialization.Primitives was moved from \Packages to the GAC.
Wondering if the iCal.Net codebase needs an update for this?

Apr 27 15:47:59 TrentApi TrentApi: [DEV] [ApiVer: 2018.4.27.2] default-enviro [07d63c2f-ca9b-4fd7-8de6-c7ab5f15f7f1]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Apr 27 15:47:59 TrentApi TrentApi: [DEV] [ApiVer: 2018.4.27.2] default-enviro [07d63c2f-ca9b-4fd7-8de6-c7ab5f15f7f1]: File name: 'System.Runtime.Serialization.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified

**Comment by rianjs** [comment]
> Does iCal.Net 4.0.6 support .NET Framework 4.7.1?

Yes. ical v4 targets .NET Standard 1.3, [which supports 4.6+](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

> Wondering if the iCal.Net codebase needs an update for this?

No, this is a bug in .NET Standard itself. There are workarounds: https://github.com/dotnet/standard/issues/481

**Comment by KwalityKoder** [comment]
> No, this is a bug in .NET Standard itself. There are workarounds: dotnet/standard#481

I have seen that link - it only mentions .Net Standard 2.0.
iCal.Net uses .Net Standard 1.3, so is it still relevant?

**Comment by rianjs** [comment]
Yes, unfortunately, it still applies.

I recently wrote a code generator to rewrite 700 csproj files so I could start consuming .NET Standard packages. I added all the workarounds described in that thread to get .NET Standard working with our legacy system. Those workarounds _do_ work. If you hit a wall after incorporating them, reply to the thread, and I'll see if I can work through it.

One of the things you may find helpful is converting from packages.config to `PackageReference`s. `PackageReference` tells nuget to compute the dependency graph and pull in the required deps. Sticking with the old `packages.config` method means you may have to flatten the graph by hand. (At least until they fix traditional Framework's .NET Standard implementation.)

**Comment by rianjs** [comment]
Oh, it looks like Visual Studio may have built-in tooling to migrate from `packages.config` to `PackageReference`s:

https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

That didn't exist in December.

Additional PackageReference documentation: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by KwalityKoder** [comment]
Great...thanks for all the information - you've been more than helpful.
I will give it a try tomorrow.

**Comment by KwalityKoder** [comment]
Unfortunately, doesn't appear to solve the issue - I will investigate further. 

Thinking about it, if I compare iCal.Net with the Automapper or NodaTime NuGet packages, they both target .NetStandard v1.3 and .NetFramework v4.5. If iCal were changed to target .NetFramework v4.7.1 (or maybe even v4.5), as well as .NetStandard v1.3, then wouldn't that also solve the issue, as we could then bypass .NetStandard and its bug?

**Comment by bartdk-be** [comment]
Any news on this topic ? Unable to run a deployed version of our ASP.NET application, using the ical library as well.

**Comment by KwalityKoder** [comment]
We managed a workaround on our .ASP .Net Web API application  by doing the following (your mileage may vary):

1) Retargeted the version of .Net Framework for all projects in solution from 4.6.x to 4.7.1 (affects csproj & app.config in each proj)
2) Changed Compilation & HttpRuntime targetFramework from 4.6.2 to 4.7.1 in web.config.
3) Removed binding re-directs for System.Runtime.Serialization.Primitives and System.Reflection from web.config.
4) Removed binding re-directs for System.Runtime.Serialization.Primitives and System.Reflection from the app.config belonging to the class library where the run-time error occurred.
5) Removed references to system.reflection & system.runtime.serialization.primitives from the class library where the run-time error occurred.
    This was done by directly deleting the reference, rather than by uninstalling properly via NuGet.

**Comment by rianjs** [comment]
Version 4.1.4 should work much better with traditional Framework applications 4.6+. Give it a go. It should “just work”.

**Comment by KwalityKoder** [comment]
Thanks a lot for fixing the issue.

**Comment by frontierteg** [comment]
.Net Standard 1.3 is .Net FrameWork 4.6
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
