### ISSUE TITLE
How to parse the RRule of google calendar to get the list of occurrences

### ISSUE THREAD

**Issue by imraan-ecsion** [ical-org/ical.net#380]
I require solution for parsing the RRule of google calendar api to return the list of occurrences.
"recurrence":["RRULE:FREQ=WEEKLY;UNTIL=20180530T182959Z;BYDAY=MO,WE"]

How can I parse the above rule to create list of occurrences.

**Comment by rianjs** [comment]
You have to deserialize the JSON, and then parse the RRULE string.

```csharp
var rrule = new RecurrencePattern("RRULE:FREQ=WEEKLY;UNTIL=20180530T182959Z;BYDAY=MO,WE");
```
