### ISSUE TITLE
Email message doesn't contain appointment

### ISSUE THREAD

**Issue by ltordai** [ical-org/ical.net#381]
Hi,
I am using iCal.Net to include appointment in email message.

Saving the email on the hard disk generates EML file, which looks perfectly all right when opened in Outlook.

The MSG file sent by SmtpClient on the other hand fails to include the appointment. Also the html text appears as plain text file.

What am I doing wrong?

Here is the piece of code adding to appointment the email:

    System.Net.Mail.SmtpClient smtpclient = new System.Net.Mail.SmtpClient();
    smtpclient.Host = "localhost"; //-------this has to given the Mailserver IP

    smtpclient.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;

    System.Net.Mime.ContentType contype = new System.Net.Mime.ContentType("text/calendar");
    contype.Parameters.Add("method", "REQUEST");
    contype.Parameters.Add("name", "Meeting.ics");
    AlternateView avCal = AlternateView.CreateAlternateViewFromString(str.ToString(), contype);
    msg.AlternateViews.Add(avCal);
    
    msg.Headers.Add("Content-class", "urn:content-classes:calendarmessage");
    
    smtpclient.Send(msg);

Any help is appreciated.
Best regards,
 Laszlo Tordai
 l.tordai@upcmail.nl

**Comment by rianjs** [comment]
You’ll have better luck asking questions about SmtpClient on a place like StackOverflow.
