### ISSUE TITLE
Create RRule by passing recurrence details

### ISSUE THREAD

**Issue by imraan-ecsion** [ical-org/ical.net#386]
How to create an RRule by passing the recurrence details of an event.
I have the following JSON value from which I need to create the Recurrence rule.

"recurrence": {
                "pattern": {
                    "type": "weekly",
                    "interval": 1,
                    "month": 0,
                    "dayOfMonth": 0,
                    "daysOfWeek": [
                        "tuesday",
                        "thursday",
                        "saturday"
                    ],
                    "firstDayOfWeek": "sunday",
                    "index": "first"
                },
                "range": {
                    "type": "endDate",
                    "startDate": "2018-07-03",
                    "endDate": "2018-07-31",
                    "recurrenceTimeZone": "West Asia Standard Time",
                    "numberOfOccurrences": 0
                }
            }

Please provide solution for the above query.

**Comment by rianjs** [comment]
Deserialize the JSON to some object and then build an RRULE

https://github.com/rianjs/ical.net/wiki/Working-with-recurring-elements
