### ISSUE TITLE
Could not find System.Reflection.TypeExtensions

### ISSUE THREAD

**Issue by drewob** [ical-org/ical.net#395]
I have a .NET Framework 4.7.1 project that references Ical.Net 4.1.2 (Nuget) and I get the following error:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    at Ical.Net.ServiceProvider.SetService(Object obj)
   at Ical.Net.CalendarObject.SetService(Object obj)
   at Ical.Net.CalendarComponents.CalendarEvent..ctor()

**Comment by rianjs** [comment]
I merged this today:
https://github.com/rianjs/ical.net/issues/392

It's in 4.1.4 -- try that.

**Comment by rianjs** [comment]
(Re-open if that doesn't clear it up.)

**Comment by drewob** [comment]
That worked. Thank you. Please note that it breaks again if I update the NodaTime package > 2.0.2

**Comment by rianjs** [comment]
Yeah I noticed that today as well. I think it’s a straightforward fix. I’ll see if I can get it in tomorrow. A hard dependency on a specific version is bad.
