### ISSUE TITLE
OccursOn returns wrong results

### ISSUE THREAD

**Issue by SashmanGH** [ical-org/ical.net#400]
Hi,

consider the following code (using Version 4.0.1):

        Dim now = New DateTime(2018, 1, 1)
        Dim later = New DateTime(2019, 12, 31)
        Dim myrule = New RecurrencePattern("FREQ=MONTHLY;BYMONTHDAY=28,29,30,31;BYSETPOS=-1;BYDAY=MO,TU,WE,TH,FR")
        Dim e = New CalendarEvent With {
                .Start = New CalDateTime(now),
                .[End] = New CalDateTime(later),
                .RecurrenceRules = New List(Of RecurrencePattern) From {
                myrule
                }
                }

        Dim occursToday1 = e.OccursOn(New CalDateTime(New Date(2018, 5, 31)))
        Dim oc = e.GetOccurrences(New DateTime(2018, 1, 1), New DateTime(2018, 12, 31))
        Dim occursToday2 = e.OccursOn(New CalDateTime(New Date(2018, 5, 31)))
        Dim occursToday3 = e.OccursOn(New CalDateTime(New Date(2018, 5, 20)))

The rrule specefies the last workday (Mon-Fri) in a month. It should return the last day in may 2018 as a valid date.

I would exprect occursToday1  and occursToday2 to be true and occursToday3 to be false. For some reason the values are like this:
occursToday1 = false
occursToday2 = true
occursToday3 = true

![ical](https://user-images.githubusercontent.com/39825767/40832326-600c82ae-658b-11e8-8b89-5db32d993bf1.png)

Is there something I am doing wrong or is this a bug?

I could workaround this by checking e.GetOccurrences(today, today.adddays(1))>2, but I would rather use OccursOn...

Thanks,
Sascha

**Comment by rianjs** [comment]
I'm not surprised. I was looking at the implementation of `OccursAt` and `OccursOn` last night, thinking they were a little strange. I'll reimplement them in terms of `GetOccurrences`, which is how I would have expected them to work.
