### ISSUE TITLE
Is there a version of ical.net that is for .Net 4.5?

### ISSUE THREAD

**Issue by CourtneyOS** [ical-org/ical.net#405]
Just wondering if there is a version of ical.net that would work for .Net 4.5. 
I'm trying to write an iCal exporter for Sharepoint 2013 and would very much like to use this tool as it will make my life so much easier. I grabbed the oldest version I could from nuget but I'm getting the following error on compilation. 

The primary reference "Ical.Net, Version=2.1.0.23684, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".

Is there a version of the GitHub source I could clone to compile my own?

**Comment by CourtneyOS** [comment]
This is resolved, nuget was automatically adding the 4.5 binaries which are compiled vs 4.5.2. 
I manually switched to 2.0 and its working after I signed the dlls.

**Comment by rianjs** [comment]
Yeah, use the latest version of 2 that you can.
