### ISSUE TITLE
PRODID not being respected after upgrade from v2 to v4

### ISSUE THREAD

**Issue by gregveres** [ical-org/ical.net#408]
Hi, 

I just upgraded from v2 to v4. After getting the code to recompile and changing all the lower case values to upper case, I am left with one difference that is showing up in my unit tests. 

The ProductId of the calendar isn't being respected when serializing calendar events. I used to set the productId and serialize an event like this:
```
           var calendar = new Ical.Net.Calendar
            {
                ProductId = "-//www.skycourt.ca//RemoteAPI/EN"
            };
            calendar.Events.Add(ev);
            var serializer = new CalendarSerializer(new SerializationContext());
```

now that ProductId string comes out like this:
`PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN`

Is there a way to get the prodid to be set to the value I want?

**Comment by gregveres** [comment]
Hmm I see that this is forced / hard coded in the serialization of a calendar on line 31 of https://github.com/rianjs/ical.net/blob/master/net-core/Ical.Net/Serialization/CalendarSerializer.cs

I am not sure what I think of that. The product is really our product, not the library that it uses. But I guess I can also see the other point of view....

**Comment by rianjs** [comment]
See release-notes.md it was a very recent change.

That’s a perspective I hadn’t considered: that it might be an
implementation detail of a larger product...

**Comment by gregveres** [comment]
I would probably recommend that if ProductId isn't set, then set it to your string. But if it is set, then the user wants to set it something that indicates their product. 

Is there a parsing benefit to having it set to your string?

**Comment by tech-nik89** [comment]
Hi,

is this issue still being discussed? I've got the same problem here and would like to identify the output as my software instead of just the library.

Thanks a lot!

**Comment by Franklin89** [comment]
Any news on this?

**Comment by gonace** [comment]
Hi
Any news on this? is this something that are going to be supported? Otherwise, we'll be stuck on an old version forever.

**Comment by Samelandslaget** [comment]
@rianjs You write in the release notes:

> 4.1.8 - (2018-06-12) - PRODID and VERSION are unconditionally set when serializing a calendar so as not to mislead consumers about where the serialized output came from. Previous behavior would use the values that came from deserialization. #403

This is all well and good as the default behavior, but what about the suggestion from @gregveres ?

> I would probably recommend that if ProductId isn't set, then set it to your string. But if it is set, then the user wants to set it something that indicates their product.

I mean, you can always do a manual replacement on the serialized string as a hacky way of setting the `PRODID`, so why not just make it a bit easier for the consumers of your package?

This isn't to say ical.net isn't a much appreciated package. Just trying to provide feedback is all.

**Comment by railapex** [comment]
Yep, just got bit by this too -- if I'm specifically setting a ProductId then I want it rendered and may be looking for that value elsewhere to know that I've generated it.

IMO, the current method of just straight overriding is bad news. If you're going to do that, make the property read only.

My proposal:
 - [ ] Make ProductId/Version properties read only
 - [ ] Restructure CalendarSerializer so that if you want to override the ProductId /Version you can derive your own CalendarSerializer and pass in the correct values

@rianjs I know you're short on time, so I'm happy to do a PR to solve this, **if** it will be accepted.

**Comment by lauxjpn** [comment]
The current implementation is an issue, because it violate the intention of the property (and thereby breaks conformance with the specs):

_(From [Internet Calendaring and Scheduling Core Object Specification (iCalendar): 3.7.3. Product Identifier](https://tools.ietf.org/html/rfc5545#section-3.7.3))_
>3.7.3.  Product Identifier
>
>   Property Name:  PRODID
>
>   Purpose:  This property specifies the identifier for the product that created the iCalendar object.
>
>   Value Type:  TEXT
>
>   Property Parameters:  IANA and non-standard property parameters can be specified on this property.
>
>   Conformance:  **The property MUST be specified once in an iCalendar object.**
>
>   Description:  **The vendor of the implementation SHOULD assure that this is a globally unique identifier**; using some technique such as an FPI value, as defined in [ISO.9070.1991].

**Comment by randbrown** [comment]
Any news on this?   Shouldn't it be the PRODUCT id, not the library id?

**Comment by lauxjpn** [comment]
@randbrown I am using the following code as a workaround:

```c#
const string productId = "-//my-company//My-Product//EN";
const string defaultProductId = "-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN";

var calendar = new Calendar
{
    ProductId = productId, // <-- makes no difference
    Method = "PUBLISH",
};

// ...

return new CalendarSerializer(calendar)
    .SerializeToString()
    // https://github.com/rianjs/ical.net/issues/408
    .Replace(defaultProductId, productId);
```

**Comment by railapex** [comment]
Good workaround!

**Comment by minichma** [comment]
It's also possible to use `ComponentSerializer` instead of `CalendarSerializer`, which doesn't have the issue.

```cs
val icalStr = (new ComponentSerializer()).SerializeToString(calendar);
```

**Comment by DreamTreem** [comment]
@minichma Thank you! it works in 2022.

**Comment by Ruud2000** [comment]
> It's also possible to use `ComponentSerializer` instead of `CalendarSerializer`, which doesn't have the issue.
> 
> ```cs
> val icalStr = (new ComponentSerializer()).SerializeToString(calendar);
> ```

Note that this approach requires you to set the `Version` property on the `Calendar`. This property is automatically populated when using the `CalendarSerializer`.
