### ISSUE TITLE
Recurrence issue in weekly

### ISSUE THREAD

**Issue by nketha** [ical-org/ical.net#409]
Recurrence issue in weekly

I have an event created on 2018-07-17 (on a Tuesday with a recurrence, "FREQ=WEEKLY;BYDAY=TU,TH,SA". The recurrence rule excludes the day when I created the event on, because it's not on WE, FR or SU.
![image](https://user-images.githubusercontent.com/39990755/42818176-c4a3241c-89ed-11e8-92e1-52b4418fc6b4.png)
![image](https://user-images.githubusercontent.com/39990755/42818828-85d50ffa-89ef-11e8-9ad8-0503fbf83a78.png)
My Scenarios show in attached screen shot

My question is: why adding one day for the selected dates

**Comment by Fuzzillogic** [comment]
I can confirm the behavior. However, the spec states: 

> The "DTSTART" property defines the first instance in the recurrence set.

So, it actually seems correct to me.

The way clients handle this differs. [Kendo](https://demos.telerik.com/kendo-ui/scheduler/index) ignores the event on the DTSTART, if it doesn't match the RRULE. So does Outlook, but it mentions "Occurs every <RRULE> effective <first occurence of RRULE>". KDE's Kontact forces the RRULE to include DTSTART, thus in the example above, it would auto-select Wednesday, which then can't be deselected.

**Comment by Fuzzillogic** [comment]
Ohh I was looking at the old and obsolete RFC 2445. As mentioned in #407, the current RFC 5545, which ical.NET supports, says the behavior in this case is "undefined".

**Comment by nketha** [comment]
Ok thank so much.
