### ISSUE TITLE
FreeBusy entry serializer

### ISSUE THREAD

**Issue by victormp1988** [ical-org/ical.net#413]
Hello,

Trying to serialize specific FreeBusy object:
            Calendar cal = new Calendar();

            CalendarEvent evt = cal.Create<CalendarEvent>();
            evt.Summary = "Test event";
            evt.Start = new CalDateTime(2010, 10, 1, 8, 0, 0);
            evt.End = new CalDateTime(2010, 10, 1, 9, 0, 0);

            cal.FreeBusy.Add(cal.GetFreeBusy(new CalDateTime(2010, 10, 1, 0, 0, 0), new CalDateTime(2010, 10, 7, 11, 59, 59)));

            var serializer = new CalendarSerializer();
            var serializedCalendar = serializer.SerializeToString(cal);

the resultant string is the following:

BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
BEGIN:VEVENT
DTEND:20101001T090000
DTSTAMP:20180810T105015Z
DTSTART:20101001T080000
SEQUENCE:0
SUMMARY:Test event
UID:d6974a0f-050b-4228-b205-fe83ed48203a
END:VEVENT
BEGIN:VFREEBUSY
DTEND:20101007T115959
DTSTAMP:20180810T125015
DTSTART:20101001T000000
**FREEBUSY:20101001T080000**
UID:928141f6-81ff-4117-8c04-05eecbe84544
END:VFREEBUSY
END:VCALENDAR

However, according with the standard I was expecting something like this:

BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
BEGIN:VEVENT
DTEND:20101001T090000
DTSTAMP:20180810T112105Z
DTSTART:20101001T080000
SEQUENCE:0
SUMMARY:Test event
UID:5cedd488-a92c-4c5c-9ea1-9e4f734f75e1
END:VEVENT
BEGIN:VFREEBUSY
DTEND:20101007T115959
DTSTAMP:20180810T132105
DTSTART:20101001T000000
**FREEBUSY:20101001T080000/PT1H**
UID:0ba2d5f0-3b33-4d83-ab8a-9237c13cd06f
END:VFREEBUSY
END:VCALENDAR

Why PeriodSerializer's SerializeToString method has the following condition?
```
// Serialize the duration
                if (!p.StartTime.HasTime)
                {
                    // Serialize the duration
                    sb.Append("/");
                    sb.Append(timeSpanSerializer.SerializeToString(p.Duration));
                }
```

**Comment by victormp1988** [comment]
Up!

**Comment by DarthSonic** [comment]
Similar problem:

```
var freeBusy = new FreeBusy()
            {
                Organizer = calendarEvent.Organizer,
                Attendees = calendarEvent.Attendees,
                DtStamp = calendarEvent.DtStamp,
                DtStart = calendarEvent.DtStart,
                DtEnd = calendarEvent.DtEnd,

            };

            freeBusy.Entries.Add(new FreeBusyEntry() { StartTime = calendarEvent.Start, EndTime = calendarEvent.End, Status = FreeBusyStatus.Busy });

            calendar.FreeBusy.AddRange(new List<FreeBusy>() { freeBusy });
```
            
 Results in FREEBUSY:201210118T080000
 
 No end of busy period.
