### ISSUE TITLE
Referenced components could not be found (.net 4.7.1)

### ISSUE THREAD

**Issue by lhj42** [ical-org/ical.net#415]
On a fresh project targeting .NET 4.7.1 adding Ical.Net nuget package pulls in a few dependencies (directly and indirectly). The two below result in warnings that the referenced components could not be found

System.Runtime.Serialization.Primitives
System.Reflection

This might be related to https://github.com/dotnet/standard/issues/567 ?

**Comment by Jasonzhangjs** [comment]
I have the same problem as you, Have you solved it?

**Comment by lhj42** [comment]
As far as I remember I think it would need to be solved in the package itself and I found no acceptable workaround. 

Our solution was to downgrade the package to version 2.3.5. This may or may not be possible for you depending on what features you rely on as this means known bugs exists but fortunately we were not using those parts.
