### ISSUE TITLE
The Fifth/Last Thursday of every Month

### ISSUE THREAD

**Issue by ram-nachiappan** [ical-org/ical.net#418]
The ical attachment (.ics) works for every case except fifth or last week of the month. I'm trying to create a recurrence for fifth or last Thursday of every month. When I open the .ics file, it says "The operation failed". Please let me know what is wrong. Thanks.

Here's the code:

{FREQ=MONTHLY;INTERVAL=3;COUNT=2;BYDAY=5SU}        
                            
![image](https://user-images.githubusercontent.com/43477366/45892838-f8aea180-bd8e-11e8-8802-c89acb43da61.png)

**Comment by minichma** [comment]
Did you check, whether this is related to #407? Maybe DTSTART doesn't match the RRULE?
