### ISSUE TITLE
System.NullReferenceException at Ical.Net.Serialization.SerializationContext.Peek

### ISSUE THREAD

**Issue by lundmikkel** [ical-org/ical.net#421]
I've had an iCal service running the last couple of months, and in that period I've gotten seemingly random `NullReferenceException` from ical.net half a dozen times. Since getting more users the last week, the error has now started appearing once a day. The error seems to happen somewhat at random and even with the same input.

I have yet to observe it locally, but I've gotten a stack trace from my production logs:

    {
        "assembly":"Ical.Net, Version=4.1.8.0, Culture=neutral, PublicKeyToken=null",
        "method":"Ical.Net.Serialization.SerializationContext.Peek",
        "level":0,
        "line":75,
        "fileName":"Ical.Net\Serialization\SerializationContext.cs"
    },
    {
        "assembly":"Ical.Net, Version=4.1.8.0, Culture=neutral, PublicKeyToken=null",
        "method":"Ical.Net.Serialization.DataTypes.StringSerializer.SerializeToString",
        "level":1,
        "line":78,
        "fileName":"Ical.Net\Serialization\DataTypes\StringSerializer.cs"
    },
    {
        "assembly":"Ical.Net, Version=4.1.8.0, Culture=neutral, PublicKeyToken=null",
        "method":"Ical.Net.Serialization.PropertySerializer.SerializeToString",
        "level":2,
        "line":38,
        "fileName":"Ical.Net\Serialization\PropertySerializer.cs"
    },
    {
        "assembly":"Ical.Net, Version=4.1.8.0, Culture=neutral, PublicKeyToken=null",
        "method":"Ical.Net.Serialization.ComponentSerializer.SerializeToString",
        "level":3,
        "line":43,
        "fileName":"Ical.Net\Serialization\ComponentSerializer.cs"
    },
    {
        "assembly":"Ical.Net, Version=4.1.8.0, Culture=neutral, PublicKeyToken=null",
        "method":"Ical.Net.Serialization.ComponentSerializer.SerializeToString",
        "level":4,
        "line":51,
        "fileName":"Ical.Net\Serialization\ComponentSerializer.cs"
    },
    {
    	// My calling code...
    }

The method failing is the `Peek` method:

    public virtual object Peek()
    {
        if (_mStack.Count > 0)
        {
            var r = _mStack.Peek();  // <- NullReferenceException thrown here
            if (r.IsAlive)
            {
                return r.Target;
            }
        }
        return null;
    }

I'm having a hard time figuring out, how `r` becomes null. [`Stack<T>` will throw an `InvalidOperationException` if the collection is empty](https://docs.microsoft.com/en-us/dotnet/api/system.collections.stack.peek), and `Push` doesn't allow null objects or references:

    public virtual void Push(object item)
    {
        if (item != null)
        {
            _mStack.Push(new WeakReference(item));
        }
    }

I'm guessing an easy way to fix the symptom is to use the null conditional operator:

    if (r?.IsAlive == true) return r.Target;

But that doesn't really solve the underlying problem. I'm hoping you have a better idea of what the problem could be.

**Comment by lundmikkel** [comment]
@rianjs No comments here?

**Comment by rianjs** [comment]
Since the null reference exception occurs when serializing to string, it might be helpful to see the code that serializes to string. :)

**Comment by lundmikkel** [comment]
The calling code looks like this:

    public class CalendarFormatter : TextOutputFormatter
    {
        private static readonly CalendarSerializer CalendarSerializer = new CalendarSerializer(new SerializationContext());

        public CalendarFormatter()
        {
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse("text/calendar"));

            SupportedEncodings.Add(Encoding.UTF8);
            SupportedEncodings.Add(Encoding.Unicode);
        }

        protected override bool CanWriteType(Type type) => typeof(Calendar).IsAssignableFrom(type);

        public override async Task WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
        {
            if (context.Object is Calendar calendar)
            {
                var iCalString = CalendarSerializer.SerializeToString(calendar);

                var body = context.HttpContext.Response.Body;
                using (var writer = context.WriterFactory(body, selectedEncoding))
                {
                    await writer.WriteAsync(iCalString);
                }
            }
        }
    }

**Comment by rianjs** [comment]
That looks reasonable and sane. The code at the deepest level there is:

```csharp
// Serialize child objects
foreach (var child in c.Children)
{
    // Get a serializer for each child object.
    var serializer = sf.Build(child.GetType(), SerializationContext) as IStringSerializer;
    sb.Append(serializer.SerializeToString(child));
}
```

Specifically `sb.Append(serializer.SerializeToString(child));`. So I would guess child is null, but `StringSerializer` returns `null` in that case; it doesn't `throw`. Weird.


What does the data look like that you're serializing? VEVENTs? VTODOs? Simple? Complex?

**Comment by lundmikkel** [comment]
VEVENTs and some time zones. Nothing too fancy. Just employee working schedules.

**Comment by lundmikkel** [comment]
FYI: I've updated the `WriteResponseBodyAsync` implementation to:

```csharp
if (context.Object is Calendar calendar)
{
    var iCalString = new CalendarSerializer(calendar).SerializeToString();

    var body = context.HttpContext.Response.Body;
    using (var writer = context.WriterFactory(body, selectedEncoding))
    {
        await writer.WriteAsync(iCalString);
    }
}
```
Creating a new `CalendarSerializer` with the `Calendar` object each time seems to do the trick.

Disclaimer: I've only had code live for a couple of days, so I'm still monitoring it.

**Comment by lundmikkel** [comment]
Okay, so after my latest update, I haven't seen any exceptions in production. I'll consider it an error on my part. Thanks for your help!
