### ISSUE TITLE
DTStart in recurrence / exclusion patterns

### ISSUE THREAD

**Issue by sbozzie** [ical-org/ical.net#425]
On an event with a DTSTART of 20181001T000000Z, recurring daily.
I would like to add an exception rule on a specific range with an EXRULE for example: 
DTSTART:20181206T101100Z;RRULE:FREQ=DAILY;COUNT=3;INTERVAL=4;WKST=MO

I can add recurrence patterns with an Until parameter - but I cannot find a way to add a pattern with a From / Start parameter in the EXRULE.

(Every day, except Christmas week for example)

**Comment by rianjs** [comment]
EXRULE is deprecated.

https://tools.ietf.org/html/rfc5545#appendix-A.3
