### ISSUE TITLE
CalDateTime sets HasTime property to false if time is 12:00 AM

### ISSUE THREAD

**Issue by rcheung9** [ical-org/ical.net#429]
If I create a new CalDateTime `new CalDateTime(dtStart)` where `dtStart` is a DateTime object with time set to 12:00 AM, the resulting CalDateTime `HasTime` property is false.

This changes the Serialization to this.

```
DTEND:20181107T013000
DTSTAMP:20181107T002112Z
DTSTART;VALUE=DATE:20181107
```

But Outlook can't parse this file into a calendar invite.  It just calls the file `not supported calendar message.ics`.

I don't know if this is an Outlook thing, but for now I just manually set `HasTime` to true after creating the CalDateTime object and it serializes into a format recognizable by Outlook.

**Comment by jasoncoding** [comment]
Just ran into this same issue on ver. 4.1.11.  Same issue in Outlook & Google calendar when using UTC dates.  Especially confusing when you are using UTC dates and only those dates at midnight UTC don't have the proper times once imported.

Appreciate the pointer rcheung9 :)
