### ISSUE TITLE
Recurrence pattern Until property that sets number of occurrence

### ISSUE THREAD

**Issue by Juniuz** [ical-org/ical.net#433]
Hi,

I have a requirement which part of the recurrence (Until property) is not limited to a date/time only value.

Is there an existing property/rule in recurrence pattern class (sets a number) that ends after a number of occurrence?  Say for example:

I have a schedule that runs every month on the 11th day, and schedule should run for 3 times only. How to set a recurrence rule for this kind of scenario?  Any examples that I can follow with?

**Comment by rianjs** [comment]
Have a look at the examples on this page:
https://github.com/rianjs/ical.net/wiki/Working-with-recurring-elements
