### ISSUE TITLE
Recurrence parser does not follow RFC 5545

### ISSUE THREAD

**Issue by Sharparam** [ical-org/ical.net#438]
There is an issue when parsing an RRULE string that does not begin with "FREQ". The current parser extracts the first occurrence of "FREQ" and everything following it, meaning that any properties that occurred before the first "FREQ" are ignored.

This is not according to [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.3.10), which states that "The rule parts are not ordered in any particular sequence.".

The problem starts with this regex pattern:

https://github.com/rianjs/ical.net/blob/master/net-core/Ical.Net/Serialization/DataTypes/RecurrencePatternSerializer.cs#L196

**Comment by rianjs** [comment]
Do you have some ics text that demonstrates the bug?

**Comment by Sharparam** [comment]
Any RRULE string where data comes before the FREQ property will have that data stripped.

![image](https://user-images.githubusercontent.com/551094/53252508-5be68c00-36bf-11e9-978e-5c2abf6cab77.png)

In the first one where FREQ is first, COUNT is parsed correctly. In the second one where COUNT comes before FREQ, it is being ignored and set to the default value.
