### ISSUE TITLE
Google Calendar compatibility issues

### ISSUE THREAD

**Issue by ramonsmits** [ical-org/ical.net#445]
Hosting an serialized to ICS file and adding that to Google Calendar as an internet calendar does not work. There is something that Google Calendar does not like about the generated file.

I also asked a Stackoverflow question about it: 
- https://stackoverflow.com/questions/55588551/google-calendar-not-showing-events-from-icalendar-ics-file-hosted-on-s3

I'm hosting it at: http://static.exyll.net/exports/bevelvoerder.ics

Serializing and uploading the ICS file into a Google Calendar works.

I currently suspect potentially 2 things:

- The order or `DTSTART`, `DTEND`, `DTSTAMP`
- The value of the timestamps not having `;VALUE=DATE-TIME`

Reason I'm suspecting these is that another calendar hosted there is shown: 

- http://static.exyll.net/f1.ics

Importing the calendar into a regular calendar works without issues and shows all events are imported.

**Comment by pierluca** [comment]
Response brought by StackOverflow:

> 
> The file contained an UTF8 BOM, this caused the following validator not to load. I'm using c# and had to use new StreamWriter(s, new UTF8Encoding(false)) instead of new StreamWriter(s, Encoding.UTF8)
> 
> http://ical-validator.herokuapp.com/urlvalidate?url=http://static.exyll.net/exports/bevelvoerder.ics
> The validator states that the ORGANIZER property is needed but that is not correct.
> 

I believe this issue can be closed.
