### ISSUE TITLE
Issue parsing ics from Beeline, Inc

### ISSUE THREAD

**Issue by lloiodice** [ical-org/ical.net#448]
We run into an ICS which has the following line:

SUMMARY; ENCODING=QUOTED-PRINTABLE:Interview:=20Kalim,=20Usraa=20(24524-1)

iCal.Net library version 4.1.11 throws an exception:
Could not parse line: 'SUMMARY; ENCODING=QUOTED-PRINTABLE:Interview:=20Kalim,=20Usraa=20(24524-1)'

   at Ical.Net.Serialization.SimpleDeserializer.ParseContentLine(SerializationContext context, String input) in C:\Gradifi\ical.net\net-core\Ical.Net\Serialization\SimpleDeserializer.cs:line 126
   at Ical.Net.Serialization.SimpleDeserializer.Deserialize(TextReader reader)+MoveNext() in C:\Gradifi\ical.net\net-core\Ical.Net\Serialization\SimpleDeserializer.cs:line 78
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Ical.Net.CalendarCollection.Load(TextReader tr) in C:\Gradifi\ical.net\net-core\Ical.Net\CalendarCollection.cs:line 34
   at Ical.Net.CalendarCollection.Load(Stream s) in C:\Gradifi\ical.net\net-core\Ical.Net\CalendarCollection.cs:line 27

Would you know why this is not supported?

Thanks in advance

**Comment by petertsu** [comment]
I have the same issue

**Comment by JamesMenzies** [comment]
I have a similar issue with fields with `QUOTED-PRINTABLE` Encoding.

I can see that problems with parsing of are already associated with test data `/src/Ical.Net.CoreUnitTests/Calendars/Serialization/Parse1.ics`.

The associated unit test asserts that the result is either a not null or a `SerializationException`.

However the field I have in source data look more like this which isn't even real `QUOTED-PRINTABLE`:
```
DESCRIPTION;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:=0D=0A=2D=2D=20=44=6F=20=6E=6F=74=20=64=65=6C=65=74=65=20=6F=72=20=63=
=68=61=6E=67=65=20=61=6E=79=20=6F=66=20=74=68=65=20=66=6F=6C=6C=6F=77=
=69=6E=67=20=74=65=78=74=2E=20=2D=2D=0D=0A=0D=0A=4A=6F=69=6E=20=57=65=
=62=45=78=20=6D=65=65=74=69=6E=67=3C=68=74=74=70=73=3A=2F=2F=63=61=70=
=63=6F=6D=2E=77=65=62=65=78=2E=63=6F=6D=2F=63=61=70=63=6F=6D=2F=6A=2E=
=70=68=70=3F=4D=54=49=44=3D=6D=63=35=65=38=31=30=30=39=63=65=30=34=34=
=35=30=30=30=30=30=30=30=30=30=30=30=30=30=30=30=30=30=30=3E=0D=0A=4D=
=65=65=74=69=6E=67=20=6E=75=6D=62=65=72=20=28=61=63=63=65=73=73=20=63=
=6F=64=65=29=3A=20=30=30=30=20=31=31=31=20=32=32=32=0D=0A=4D=65=65=74=
=69=6E=67=20=70=61=73=73=77=6F=72=64=3A=20=51=30=30=30=30=30=30=30=0D=
=0A=0D=0A=4A=6F=69=6E=20=66=72=6F=6D=20=61=20=76=69=64=65=6F=20=73=79=
=73=74=65=6D=20=6F=72=20=61=70=70=6C=69=63=61=74=69=6F=6E=0D=0A=44=69=
=61=6C=20=30=34=35=34=39=30=30=35=36=40=63=61=70=63=6F=6D=2E=77=65=62=
=65=78=2E=63=6F=6D=3C=73=69=70=3A=30=34=35=34=39=30=30=35=36=40=63=61=
=70=63=6F=6D=2E=77=65=62=65=78=2E=63=6F=6D=3E=0D=0A=0D=0A=0D=0A=4A=6F=
=69=6E=20=62=79=20=70=68=6F=6E=65=0D=0A=2B=30=20=30=30=30=20=36=30=36=
=20=39=34=36=36=20=55=53=20=54=6F=6C=6C=0D=0A=2B=30=20=38=36=36=20=30=
=38=30=20=30=30=36=36=20=55=53=20=54=6F=6C=6C=20=46=72=65=65=0D=0A=47=
=6C=6F=62=61=6C=20=63=61=6C=6C=2D=69=6E=20=6E=75=6D=62=65=72=73=3C=68=
=74=74=70=73=3A=2F=2F=63=61=70=63=6F=6D=2E=77=65=62=65=78=2E=63=6F=6D=
=2F=63=61=70=63=6F=6D=2F=67=6C=6F=62=61=6C=63=61=6C=6C=69=6E=2E=70=68=
=70=3F=73=65=72=76=69=63=65=54=79=70=65=3D=4D=43=26=45=44=3D=34=38=30=
=30=30=30=30=30=30=26=74=6F=6C=6C=46=72=65=65=3D=30=3E=20=20=7C=20=20=
=54=6F=6C=6C=2D=66=72=65=65=20=63=61=6C=6C=69=6E=67=20=72=65=73=74=72=
=69=63=74=69=6F=6E=73=3C=68=74=74=70=73=3A=2F=2F=77=77=77=2E=77=65=62=
=65=78=2E=63=6F=6D=2F=70=64=66=2F=74=6F=6C=6C=66=72=65=65=5F=72=65=73=
=74=72=69=63=74=69=6F=6E=73=2E=70=64=66=3E=0D=0A=0D=0A
```

And I am expecting the description field to contain something like:

```
-- Do not delete or change any of the following text. --

Join WebEx meeting<https://capcom.webex.com/capcom/j.php?MTID=mc5e81009ce0445000000000000000000>
Meeting number (access code): 000 111 222
Meeting password: Q0000000

Join from a video system or application
Dial 045490056@capcom.webex.com<sip:045490056@capcom.webex.com>


Join by phone
+0 000 606 9466 US Toll
+0 866 080 0066 US Toll Free
Global call-in numbers<https://capcom.webex.com/capcom/globalcallin.php?serviceType=MC&ED=480000000&tollFree=0>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>
```
