### ISSUE TITLE
calendar.GetOcurrences vs event.GetOcurrences

### ISSUE THREAD

**Issue by suarezhar** [ical-org/ical.net#456]
Hi,
I would like to know when to use calendar.GetOcurrences() and event.GetOcurrences(). Also what is the difference between them.
Here (_**https://github.com/rianjs/ical.net/wiki/Working-with-recurring-elements#daily-for-the-month-of-july**_) you use calendar.GetOcurrences() and
in this one (**_https://github.com/rianjs/ical.net/wiki/Working-with-recurring-elements#every-other-tuesday-until-the-end-of-the-year_**) you use event.GetOcurrences()

**Comment by ghost** [comment]
A calendar can have many events, events can have many occurrences.

**Example**:  You run a sportsball club and keep a calendar.  Every Wednesday is practice (an `Event`  which has a `RecurrenceRule` for every Wednesday).  The first Friday of every month is game night (a different `Event` based on a `RecurrenceRule` for the first Friday of the month). 

`practiceEvent.GetOccurences()` returns each instance of Wednesday practice.

`gameEvent.GetOccurences()` returns each instance of monthly game night.

`sportsballCalendar.GetOccurences()` gets all occurrences of all events.

**Comment by suarezhar** [comment]
Thank you @arcooke for your help!
