### ISSUE TITLE
Support for .NET Core 3

### ISSUE THREAD

**Issue by pantonis** [ical-org/ical.net#475]
Does this library supports .NET Core 3?

**Comment by JensMertelmeyer** [comment]
~~I am just getting started with .NET (Core 3.0), so I could be wrong. But to me it seems it's not compatible. I'm getting several nuget NU1605 errors (https://docs.microsoft.com/nuget/reference/errors-and-warnings/nu1605)~~

While I couldn't get 4.1.11 to work, 3.0.15 seems to work fine with .Net Core 3 🙂

**Comment by pantonis** [comment]
@JensMertelmeyer 3.0.15 is an old version I suppose with bugs that were resolved after that version
