### ISSUE TITLE
[Question] How can I get the next occurrence?

### ISSUE THREAD

**Issue by jeremyVignelles** [ical-org/ical.net#477]
I have seen that there are options to get occurrences from a start date time to a specific date time, but is it possible to get the next occurrence of a specific event?

What I would like is something like:

```cs
DateTime? next = calendar.GetNextOccurrence();
```

Maybe an overload that accepts a starting date would be useful too.

**Comment by gilmatok** [comment]
@jeremyVignelles Have you found a solution for this?

**Comment by jeremyVignelles** [comment]
Maybe, I don't remember. it's been 4 years and I don't work for the same company anymore.

**Comment by skay97** [comment]
@gilmatok Did you figure this out?
