### ISSUE TITLE
Grouping Multiple Events

### ISSUE THREAD

**Issue by skywalker1kris** [ical-org/ical.net#486]
Hi,

I am trying to group multiple events in a single attachment. When the user tries to select this attachment to add to their calendar, it only adds the first event and skips all other events. 
If I try to set the Method type to Publish, it creates a new calendar and adds both the events.
Please let me know if there is anything wrong in the below code and any help would be greatly appreciated.

I need the Method type set to Request so I can use this to track the status of attendees if they have added to their calendar or not.

BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 2.2//EN
VERSION:2.0
X-PRIMARY-CALENDAR:TRUE
BEGIN:VEVENT
ATTENDEE;CN=Testing User;RSVP=TRUE:mailto:tuser@hwt.org
DTEND:20200426T143500
DTSTAMP:20200324T185145Z
DTSTART:20200426T135000
LOCATION:Webinar
ORGANIZER;CN=Testing User:mailto:tuser@hwt.org
SEQUENCE:0
SUMMARY:Neutral Testing
UID:Event-5998
BEGIN:VALARM
ACTION:Display
DURATION:PT15M
REPEAT:1
SUMMARY:Reminder: {0}Professional Testing
TRIGGER:-P1D
END:VALARM
END:VEVENT
BEGIN:VEVENT
ATTENDEE;CN=Testing User;RSVP=TRUE:mailto:tuser@hwt.org
DTEND:20200425T145000
DTSTAMP:20200324T185146Z
DTSTART:20200425T135000
LOCATION:Webinar
ORGANIZER;CN=Testing User:mailto:tuser@hwt.org
SEQUENCE:0
SUMMARY:High Testing
UID:Event-5999
BEGIN:VALARM
ACTION:Display
DURATION:PT15M
REPEAT:1
SUMMARY:Reminder: {0}Professional Testing
TRIGGER:-P1D
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by thommelutten** [comment]
Did you get this to work? I am encountering the same problem.

An invitation with multiple events, where only the first one is added to the calender.
