### ISSUE TITLE
Outlook TimeZone America/New_york after Daylight saving

### ISSUE THREAD

**Issue by TIN-123** [ical-org/ical.net#487]
Hi, 

I have been trying to find a solution in forums and blogs and wasn't able to find any. So I would appreciate any help on the following situation.

We are using ical.net version 4.1.11 with the following result:

> BEGIN:VCALENDAR
> METHOD:REQUEST
> PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
> VERSION:2.0
> BEGIN:VEVENT
> DESCRIPTION:\n\nCO-RELATION: The Art of Unity\n\nCultural Center
> DTEND;TZID=America/New_York:20200311T190000
> DTSTAMP:20200206T160813Z
> DTSTART;TZID=America/New_York:20200311T173000
> LAST-MODIFIED;TZID=America/New_York:20200310T113936
> LOCATION:Cultural Center
> ORGANIZER:mailto:no-reply@noemail.com
> SEQUENCE:9
> STATUS:CONFIRMED
> SUMMARY:CO-RELATION: The Art of Unity
> UID:12212
> BEGIN:VALARM
> ACTION:AUDIO
> DESCRIPTION:Reminder
> DURATION:PT15M
> TRIGGER:-PT15M
> END:VALARM
> END:VEVENT
> BEGIN:VTIMEZONE
> TZID:America/New_York
> X-LIC-LOCATION:America/New_York
> END:VTIMEZONE
> END:VCALENDAR
> 

The TimeZone C# code is :

```

                cal.AddTimeZone(new VTimeZone("America/New_York"));

                evt.Start = new CalDateTime(pEvent.StartDate, "America/New_York");
                evt.End = new CalDateTime(pEvent.EndDate, "America/New_York");
                evt.LastModified = new CalDateTime(DateTime.Now, "America/New_York");
          
```

This was working fine until last daylight saving change, from then in outlook is off by one hour. It works fine in Google and other calendars.

It seems that Outlook doesn't understand that timezone, I would like help in how to make an iCal that can be understand by all calendars for this timezone.

Thanks!

**Comment by GuiSevero** [comment]
I'm having the same issue

**Comment by GuiSevero** [comment]
@TIN-123 I think I found the solution.

by using this line: ` calendar.AddTimeZone(VTimeZone.FromDateTimeZone(tzid));`

With this, the serialization added the proper daylight info at the VTimezone:

```
BEGIN:VTIMEZONE
TZID:America/New_York
X-LIC-LOCATION:America/New_York
BEGIN:STANDARD
DTSTART:20181104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZNAME:EST
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20190310T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZNAME:EDT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
```

**Comment by TIN-123** [comment]
Thanks @GuiSevero ! I did some tests and your solution seems to work, I will give it a try
