### ISSUE TITLE
Rebuild ical.NET with latest NodaTime

### ISSUE THREAD

**Issue by RobotGizmo** [ical-org/ical.net#492]
ical.NET is currently being built against a super-old version of NodaTime which is causing issues for us and others. I believe these issues can be resolved by updating the NodaTime reference in ical.NET to the latest version (currently 2.4.8):

- https://github.com/rianjs/ical.net/issues/488
- https://github.com/rianjs/ical.net/issues/465
- https://github.com/rianjs/ical.net/issues/440

In the ical.NET project file it's referencing NodaTime 1.3.1, it would be amazing if this can be updated to the latest. Thanks!

**Comment by davidroth** [comment]
see: https://github.com/rianjs/ical.net/pull/499
