### ISSUE TITLE
Updateable calendar events

### ISSUE THREAD

**Issue by febsocal** [ical-org/ical.net#494]
How can i have a calendar event that does not need user's interaction to add to their calendar and can be updated (that is reschedule).

**Comment by rmed1na** [comment]
@febsocal check this out: https://tools.ietf.org/html/rfc5546#section-3.2.1

basically: 
1. Set the Method property of the calendar to "REQUEST".
2. Make sure the event is still the same UID.
3. Set a calendar event Status of  "CONFIRMED".
4. Make sure Sequence number is higher than the previous appointment.

This works fine for me on all tested email clients (Gmail, Outlook, iOS, Win10 Mail Client)
