### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DanAvni** [ical-org/ical.net#495]
I see no updates for this project over the last year+ and no responses to issues raised here. Is this project dead? is there an alternative?

**Comment by rianjs** [comment]
Dead? No. Back burnered? Yes. 

Like most open source software that people actually use, this was subsidized by employer. I’m no longer at that employer so it doesn’t get worked on. 

It’s fairly mature, so it’s going to have comparatively fewer updates anyway.

**Comment by josteink** [comment]
Hey @rianjs.

That's absolutely fair. As a fellow open-source maintainer, I know how that can feel.

That said... There's a quite few registered issues and PRs, and clearly a *community* out there wanting to help out. Have you considered looking for a co-maintainer for this project to help reduce the backlog?

There might even be people out there employed by companies which has a similar interest as your former employee in keeping this library up to date and working! (hint hint) :laughing:

**Comment by rianjs** [comment]
I've been thinking about this more over the last few weeks. I think I've gotten over the "Eventually I'll have time, energy, and interest", and I'm willing to expand the scope of maintainers. I'm also less of a control freak than I used to be; I think there's probably more value that can be unlocked with more people, even if the code to get it done isn't what I would write.

There have been a few people that have opened high-quality PRs. @beriniwlew , @ie-zero, and I think probably @davidroth. I don't know if they have the time, energy, and desire to actually carry the project forward. I had hoped that @chescock and @jonathanbrecher would, but alas. Not their circus, not their monkeys.

Doing this isn't something that I would jump into lightly. It takes time and energy over a sustained period of time. Half the "issues" people have aren't with ical.net, they're with understanding the iCalendar format, and how other programs interact with it -- usually Outlook or Google Calendar.

**Comment by josteink** [comment]
> I've been thinking about this more over the last few weeks. I think I've gotten over the "Eventually I'll have time, energy, and interest", and I'm willing to expand the scope of maintainers.

I've been doing this for a few projects I no longer have an active interest in or ability to contribute in, or for other reasons no longer have the drive to keep going forward. Once you get over it, and get it done, it feels really good and leaves you more energy for your other efforts.

Definitely recommended.

> There have been a few people that have opened high-quality PRs

And I'm sure that namedropping them here will help bring forward those who feel they might rise up to the task. :smiley: 

> Doing this isn't something that I would jump into lightly. 

An absolutely fair warning. For now I'm happy just to have helped stir some discussion around this topic. If nothing concrete comes out of that, maybe I'll be back later, to see if you still need/want some help.

**Comment by davidroth** [comment]
Thanks @rianjs for offering maintainership. But to be honest, I am not passionate about maintaining this library because ICal is not a domain that interests me very much ;-)  My PR was just a means to an end. (I needed it for a project).
That being said, I`d be very happy to finish my [MR](https://github.com/rianjs/ical.net/pull/499) because I think this library deserves a clean .net standard 2.0 package 😊

**Comment by beriniwlew** [comment]
Thanks for the shoutout @rianjs .    So far, it's working quite well for us, but I imagine we'll circle back around it for newer projects.  If we find any issues, we'll help to contribute.

**Comment by beriniwlew** [comment]
Fact of the matter is (IMHO) - we need a newer, open-source standard for handling calendar info.

**Comment by ie-zero** [comment]
@rianjs Thank you for kind words. 

Unfortunately, I cannot take the responsibility of maintaining this library but would keep an eye out in case I can help with anything.

**Comment by ie-zero** [comment]
@beriniwlew - Apparently the IETF agrees with you that the standard has some issues 

> 1.1.  Motivation and Relation to iCalendar and jCal
>
>   The iCalendar data format [RFC5545], a widely deployed interchange
>   format for calendaring and scheduling data, has served calendaring
>   vendors for a long while, but contains some ambiguities and pitfalls
>   that can not be overcome without backward-incompatible changes.

This is why there is a IETF working group to define a new standard named *JSCalendar*
https://datatracker.ietf.org/doc/draft-ietf-calext-jscalendar/

However, the JSCalendar is still a draft which I would expect to take a few years to finalise.

**Comment by beriniwlew** [comment]
> However, the JSCalendar is still a draft which I would expect to take a few years to finalise.

So by the time it's finalized in triplicate, we'll need a new format.  ;-)

**Comment by mpinkus** [comment]
so @rianjs what would it take to get a stable standard 2.1 version nuget deployed? I may consider a corporate sponsored  engagement for the benefit of myself and the project. We use it quite a lot. Any blockers other than lack of motivation?

**Comment by rianjs** [comment]
Time and interest is the main one. Money could persuade me to give up some of my limited free time. (3 year olds take up a lot of time and energy on weekends!)

**Comment by rianjs** [comment]
OTOH, if someone proposes a nuget 2.1 PR that looks reasonable, I would absolutely consider merging it.

**Comment by mpinkus** [comment]
BTW, you could get to core 3.1 with a nuget update and build, which would at least be relevant to current projects...drop me a DM at mike.pinkus@gmail.com on cost to get to 2.1 and/or v5.0.0-rc.2, I agree paid work is the best kind ;)

**Comment by DaleyKD** [comment]
I'd love to see @davidroth 's MR complete.  For now, we'll use his fork since it's got a lot of updates we need.

**Comment by axunonb** [comment]
@rianjs If you’re still interested in iCal.NET, I’d be happy to lend a helping hand as a co-maintainer.
