### ISSUE TITLE
Issue creating a week day recurrent event in the weekend 

### ISSUE THREAD

**Issue by 3nriqu390** [ical-org/ical.net#501]
When creating a weekday event with this recurrence rule `recurrence: "RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"` , if the event its created on a weekend day, it creates an event on the day the event was created, the rest of the weekends have no problem.

**Comment by rootGst** [comment]
@3nriqu390 you already answered yourself.
> the event its created on a weekend day

You defined an actual event that occurs on a weekend day.  `RRULE` only causes, that this actual event will be additionally repeated on Mondays, Tuesdays, Wednesdays, Thursdays and Fridays, forever.
