### ISSUE TITLE
Start time at midnight issue

### ISSUE THREAD

**Issue by m1is** [ical-org/ical.net#509]
If you set the Start of a SendCalendarEvent using a date that's at exactly midnight like the following it doesn't render out the DTSTART correctly.

calEvent.Start = new CalDateTime(DateTime.UtcNow.Date);

It renders out like the following:
DTSTART;VALUE=DATE:20210217

When it should probably render out as:
DTSTART:20210217T000000Z

**Comment by rootGst** [comment]
It look like, that this issues also causes that the result of `GetOccurrences` does not provide the time of day for an event defined like this:
```
        // Every Day at hour 11 and hour 14, for 14 occurrences
        var tomorrow = DateTime.Now.Date.AddDays(1);
        var rrule = new RecurrencePattern(FrequencyType.Daily, 1) 
        {
            Count = 14,
            ByHour = new List<int> { 11, 14}
        };

        var calendarEvent = new CalendarEvent
        {
            Start = new CalDateTime(tomorrow), 
            RecurrenceRules = new List<RecurrencePattern> { rrule },
        };

        var calendar = new Calendar();
        calendar.Events.Add(calendarEvent);
        // calendar.RecurrenceEvaluationMode = RecurrenceEvaluationModeType.AdjustAutomatically;
        var occurrences = calendar.GetOccurrences(new CalDateTime(DateTime.Now.Date), new CalDateTime(DateTime.Now.Date.AddDays(50)));
```

**Comment by kellcomnet2** [comment]
Just ran into this myself, is there a workaround currently?

**Comment by kellcomnet2** [comment]
FYI this is what I am doing and it seems to fix the issue
if (!cdtStart.HasTime) cdtStart.HasTime = true;
if (!cdtEnd.HasTime) cdtEnd.HasTime = true;

**Comment by m1is** [comment]
Thanks, a cleaner solution for the bug than mine.

**Comment by brbarnett** [comment]
> FYI this is what I am doing and it seems to fix the issue if (!cdtStart.HasTime) cdtStart.HasTime = true; if (!cdtEnd.HasTime) cdtEnd.HasTime = true;

In my case, all of my dates (even those at midnight) are _meant_ to have a time, so I just set `HasTime = true` on every record now. This is exactly the right solution. Thanks, @kellcomnet2
