### ISSUE TITLE
[IOS] Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive.

### ISSUE THREAD

**Issue by thanoue** [ical-org/ical.net#510]
i'got this issue on IOS platform: "Both COUNT and UNTIL cannot be supplied together; they are mutually exclusive"
but my calendar file jus has UNTIL property inside VEVENT. It't working fine on Android but i don't know why i've got that error on IOS
thanks

this is my ics file:

BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
BEGIN:VEVENT
ATTACH;VALUE=BINARY;ENCODING=BASE64:W3siRmllbGROYW1lIjoiTUFTSyBSRVFVSVJFRC
 IsIlZhbHVlIjp0cnVlfSx7IkZpZWxkTmFtZSI6IkFkZHJlc3MiLCJWYWx1ZSI6IjIwMCBEdW9
 uZyBkaW5oIGhvaSJ9LHsiRmllbGROYW1lIjoiTWluQWdlIiwiVmFsdWUiOjIwfV0=
DESCRIPTION:hhii
DTEND;VALUE=DATE:20210321
DTSTAMP:20210311T075648Z
DTSTART;VALUE=DATE:20210311
GEO:100.018000;10.019200
LOCATION:office HCM
ORGANIZER;CN=HCM:
RRULE:FREQ=WEEKLY;UNTIL=20210331T075627Z
SEQUENCE:0
SUMMARY:TEST NAME
UID:9ed9d56d-ef1f-4422-a801-36f98d2f46b2
END:VEVENT
END:VCALENDAR

**Comment by winstonpang** [comment]
Encountered the same issue. Simply constructing the RecurrencePattern object with this RRULE "FREQ=DAILY;UNTIL=20210928T140000Z" causes the exception to occur.
