### ISSUE TITLE
Make someone the lead developer/maintainer who has got time on their hands

### ISSUE THREAD

**Issue by lauxjpn** [ical-org/ical.net#511]
@rianjs As it is apparent, that you have other things on your mind, you should transfer the development and support of this project to active members of the community.

This is preferable over the community creating a fork and continuing development from there, since this package is the number one on nuget in regards to iCalendar support and the community will profit from easy discoverability of its continued development under the same name.

**Comment by rianjs** [comment]
https://github.com/rianjs/ical.net/issues/495
