### ISSUE TITLE
Get Featured as Nuget Package Of The Week

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ical-org/ical.net#52]
@rianjs when you are ready, I can shoot this package over to someone at Microsoft and try to get it featured as a Nuget package of the week.

![](https://media3.giphy.com/media/SwtycbxWfb1N6/giphy.gif)

**Comment by rianjs** [comment]
That GIF: :+1: 

Give me a bit. I'd like to get a better handle on the serialization bugs, and determine how serious they are. If they're bad, I'd like to fix them before advertising this to the world.

**Comment by khalidabuhakmeh** [comment]
Ok, no worries :)

**Comment by rianjs** [comment]
Ready when you are. :+1:
