### ISSUE TITLE
How to create a recurrence pattern for the last day, weekday or weekend day of the month?

### ISSUE THREAD

**Issue by cryo75** [ical-org/ical.net#532]
The following example creates a pattern for the last Sunday of every month:

```csharp
var rrule = new RecurrencePattern(FrequencyType.Monthly, 1)
{
    ByDay = new List<IWeekDay> { new WeekDay(DayOfWeek.Sunday, FrequencyOccurrence.Last) },
};
```

But how can I add a pattern for the last day or workday of the month, or the last weekend day of the month?

**Comment by dgreenway** [comment]
I found this handy tool https://www.textmagic.com/free-tools/rrule-generator which implies something like 

```csharp
var rrule = new RecurrencePattern("FREQ=MONTHLY;BYSETPOS=-1;BYDAY=MO,TU,WE,TH,FR;INTERVAL=1");
```

Last weekend Day would use `BYDAY=SA,SU` instead.

**Comment by cryo75** [comment]
Thanks. That should get me going!!
