### ISSUE TITLE
Better Nuget Logo

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ical-org/ical.net#76]
![compact_icalnet_logo](https://cloud.githubusercontent.com/assets/228256/17086844/69679f54-51ca-11e6-84cb-a2021b65d637.png)

This will look better on Nuget.org.

**Comment by khalidabuhakmeh** [comment]
![icalnet_150px](https://cloud.githubusercontent.com/assets/228256/17086855/a98eeea2-51ca-11e6-95f6-c9c56100084f.png)

150px x 150px

**Comment by rianjs** [comment]
Looks good - can you open a PR to put the logos in a `graphics` directory (or whatever), and update the nuspec file?

**Comment by khalidabuhakmeh** [comment]
sure, the logo / nuget won't be updated until the next deployment to Nuget.org.
