### ISSUE TITLE
UTC midnight is assumed not to have a timezone component

### ISSUE THREAD

**Issue by mcshaz** [ical-org/ical.net#77]
Many properties, in order to meet the spec, should have a dateTime in UTC

currently, the CalDateTime Initializer method has the code `HasTime = value.Second != 0 || value.Minute != 0 || value.Hour != 0;`

that is to say if the developer want's to set a time for the DtStart property of a FreeBusy component, the period they want starts at 8 am and they are on a +08:00 timezone (25% of the world's population live in this timezone!), they have to know to explicitly set `HasTime = True` in order to serialize correctly, and they would presumably not even be thinking what the UTC time is.

I would propose creating a CalDate class which inherits from CalDateTime, and has constructors accepting year, month, day or a DateTime, and sets the HasTime property to false (I would also make the setter for HasTime protected, with the base CalDateTime implementation always returning True (i.e. not performing the check in the initilizer function above), although that would be a breaking change and so possibly best done in a step wise pattern with an obsolete attribute on the setter).

in the interim, I could make the assignment to HasTime in the initializer a tiny bit more robust with something like `HasTime = IsUniversalTime || value.TimeOfDay.Ticks!=0;`

Thoughts? Could you suggest a better pattern? 

Thank you for your patience with all these issues.

**Comment by rianjs** [comment]
In a perfect world, `HasTime` wouldn't exist at all. In a better (but not perfect) world, it would be an expression body that returns true if there's a time component associated with the underlying `DateTime`, otherwise false.

Back in April, I tried to make it getter-only, but was unsuccessful. There are serialization routines that manually fiddle with this property, setting it to true in some cases, and setting it to false in others. Making the property an expression body broke several unit tests (I don't remember which ones). That this property exists at all irritates me to no end.

Anything you can do to make this property either 1) go away, or 2) make it a getter-only method would be an improvement.

## 

With regards to `CalDateTime` on the whole... I think most of the class probably shouldn't exist. I don't see why it can't (in theory) be a class that has a `DateTimeOffset` and a valid IANA, BCL, or serialized time zone string. Everything else can be derived from these two properties, and the heavy lifting of time zone conversions can use NodaTime types instead. Instead, we have this mishmash of nonsense when you unroll all the interface sub-dependencies; it's basically all `DateTime` operations plus some weird service provider dependencies.

``` csharp
public ICalendarParameterCollection Parameters { get; }
public void CopyFrom(ICopyable obj)
public T Copy<T>()
public object GetService(Type serviceType)
public object GetService(string name)
public T GetService<T>()
public T GetService<T>(string name)
public void SetService(string name, object obj)
public void SetService(object obj)
public void RemoveService(Type type)
public void RemoveService(string name)
public Type GetValueType()
public void SetValueType(string type)
public ICalendarObject AssociatedObject { get; set; }
public ICalendar Calendar { get; }
public string Language { get; set; }
public string Encoding { get; set; }
public int CompareTo(IDateTime other)
public string ToString(string format, IFormatProvider formatProvider)
public DateTime AsSystemLocal { get; }
public DateTime AsUtc { get; }
public bool IsUniversalTime { get; set; }
public string TimeZoneName { get; }
public DateTime Value { get; set; }
public bool HasDate { get; set; }
public bool HasTime { get; set; }
public string TzId { get; set; }
public int Year { get; }
public int Month { get; }
public int Day { get; }
public int Hour { get; }
public int Minute { get; }
public int Second { get; }
public int Millisecond { get; }
public long Ticks { get; }
public DayOfWeek DayOfWeek { get; }
public DateTime Date { get; }
public IDateTime ToTimeZone(string newTimeZone)
public IDateTime Add(TimeSpan ts)
public IDateTime Subtract(TimeSpan ts)
public TimeSpan Subtract(IDateTime dt)
public IDateTime AddYears(int years)
public IDateTime AddMonths(int months)
public IDateTime AddDays(int days)
public IDateTime AddHours(int hours)
public IDateTime AddMinutes(int minutes)
public IDateTime AddSeconds(int seconds)
public IDateTime AddMilliseconds(int milliseconds)
public IDateTime AddTicks(long ticks)
public bool LessThan(IDateTime dt)
public bool GreaterThan(IDateTime dt)
public bool LessThanOrEqual(IDateTime dt)
public bool GreaterThanOrEqual(IDateTime dt)
public void AssociateWith(IDateTime dt)
```

This type makes me say "WTF" more than any other type, including the stuff in ical.net.collections.

**Comment by mcshaz** [comment]
I couldn't agree more. 

For the interim though I have just removed setting HasTime based on whether it is UTC midnight, and left a constructor comment telling the developer that if they are using one of the DateTime constructor overloads, they should also set HasTime = false if they want a date only. Otherwise (in its current form) occasional calendar objects will be serialised very incorrectly (8am Fri is quite different to all day friday). As people tend to set appointments on the half hour, this problem would be stumbled upon, but too infrequently to be easy to track.

**Comment by rianjs** [comment]
Sounds reasonable.

**Comment by brianrutter** [comment]
Having a similar issue:
Adding an event with time 7:00 PM in EST, converting to UTC -5, makes the time 00:00, which is midnight. This then drops the time when serializing to string.

var calendar = new Ical.Net.Calendar();
calendar.ProductId = "Test";
calendar.Method = "PUBLISH";
var e = new Event()
{
DtStart = new CalDateTime(DateTime.Parse("1/1/2017 7:00:00 PM").ToUniversalTime()),
DtEnd = new CalDateTime(DateTime.Parse("1/1/2017 10:00:00 PM").ToUniversalTime()),
Summary = "Sample1",
Uid = "12345"
};

Console.Write(e.DtStart.HasTime); //Is showing False
calendar.Events.Add(e);
var serializer = new CalendarSerializer(new SerializationContext());

var serializedCalendar = serializer.SerializeToString(calendar);
return serializedCalendar;

**Comment by rianjs** [comment]
As a general note, it's difficult to distinguish between `DateTime(2016, 8, 28)` and `new DateTime(2016, 8, 28, 0, 0, 0)` -- both of them have a `TimeOfDay` value of `TimeSpan.Zero`.

The branch I pushed to just above this comment sets `HasTime = true` for everything. It didn't break any unit tests (woah!), so maybe it's OK. I need to think a little more about what `HasTime` is being used as a proxy for before I merge it.

**Comment by aluxnimm** [comment]
If HasTime = true for everything, how can you serialize something like 
`DTSTART;VALUE=DATE:20100101`

**Comment by MartinRothschink** [comment]
2.2.14 currently has the issue that deserialization goes wrong:
`DTSTART;VALUE=DATE:20100101` -> `HasTime = false`
`DTSTART;TZID=W. Europe Standard Time:20160101T000000` -> `HasTime = false`and that's wrong

From my point of view I prefer `HasTime=true`for everything.
