### ISSUE TITLE
Target RFC5545 and possibly RFC7265

### ISSUE THREAD

**Issue by chrisjmccrum** [ical-org/ical.net#84]
Hey this may just an oversight but I noticed the readme said:

> It's aimed at providing full RFC 2445 compliance

RFC 2445 was made obsolete by RFC5545 so we should probably target that instead. Also, I was wondering if there was a roadmap to use jCal according to (RFC7265)?

https://tools.ietf.org/html/rfc5545
https://tools.ietf.org/html/rfc7265

**Comment by rianjs** [comment]
From @terebi42 in #96 

> https://tools.ietf.org/html/rfc7529
> 
> https://stackoverflow.com/questions/35757778/rrule-for-repeating-monthly-on-the-31st-or-closest-day

**Comment by rianjs** [comment]
267ecadb84c94f8260b50c029a43f9a2f943581b
