### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ical-org/ical.net#86]
This project should setup a CI build server to do the following:
- Build every incoming PR against `master`
- Run all existing and new unit tests
- Attempt to build and deploy to Nuget if the version is bumped.

This will help foster more collaboration and an understanding of why or why not a PR can be merged.

Also, as a side note: look into https://lgtm.co as potential point of collaboration.

**Comment by khalidabuhakmeh** [comment]
AppVeyor is a really good contender :)

**Comment by khalidabuhakmeh** [comment]
Ran a test on AppVeyor and it worked, but has a failing test.

![screen shot 2016-08-03 at 9 49 09 am](https://cloud.githubusercontent.com/assets/228256/17367843/a26584c8-595f-11e6-998e-4acf9296a5d0.png)

**Comment by rianjs** [comment]
I'm on board with this, and with the (unexpected) number of contributors who aren't me ( :smile: ), the time definitely seems right. Do you want to take it on?

**Comment by kdaveid** [comment]
I don't see why this should be affected by #89. We did not have any STANDARD or DAYLIGHT collections to begin with. Shouldn't it be referenced to #58? 
Anyhow, the test is being skipped by VS because of ignore attribute:

```
[Test, Category("Serialization"), Ignore("TODO: standard time, for NZ standard time (current example)")]
public void TimeZoneSerialize()
{
...
}
```

**Comment by khalidabuhakmeh** [comment]
I ignored that before #89. Was trying to get a rough idea of how to get AppVeyor running.

**Comment by khalidabuhakmeh** [comment]
The build passes on AppVeyor, but I need the ability to setup the integration through the repo settings.

**Comment by rianjs** [comment]
What do the settings need to be?

(If they shouldn't be posted publicly, email me, and we can figure something out. Which reminds me, I'd like to make ical.net into an organization or project--whatever github calls that notion--instead of a repo under my personal account. I think that would work around this problem(?), too.)
