### ISSUE TITLE
Issue with deleted recurring events

### ISSUE THREAD

**Issue by vikramkhalsa** [ical-org/ical.net#91]
I'm having an issue with exceptions to recurring events, specifically date exceptions that should be omitted when you call GetOccurences. 

In my sample file, i have:
RRULE:FREQ=WEEKLY;COUNT=35;BYDAY=TU,TH
EXDATE;TZID=America/Los_Angeles:20160823T123000
EXDATE;TZID=America/Los_Angeles:20160818T123000
EXDATE;TZID=America/Los_Angeles:20160816T123000

When I call GetOccurences, only the first exdate is omitted, but the others are still present. 
I looked at event.ExceptionDates, and all 3 are present. I dug in and found out that something is happening in the Evaluate function.  On line 32 in PeriodListEvaluator.cs - periods.UnionWith(_mPeriodList);  _mPeriodList only has the first exception date in it. The other 2 are missing. So when the union is done, only the first exception date is retained. I haven't been able to figure out why the PeriodList isn't getting the other 2 dates. 

Any ideas? Is this known?  I believe when I had all the exception dates comma separated on one line it worked..

**Comment by rianjs** [comment]
Do you mind opening a pull request that adds a broken unit test that asserts the right thing, and references this issue number?

**Comment by rianjs** [comment]
`RRULE`s can't be evaluated in a vacuum like this. You need the `VEVENT` or `VALARM` that goes along with it. Feel free to re-open with the complete example.
