### ISSUE TITLE
Broken Example: Thanksgiving

### ISSUE THREAD

**Issue by erpeters** [ical-org/ical.net#95]
The example for Thanksgiving (https://github.com/rianjs/ical.net/wiki/Working-with-recurring-elements#the-fourth-thursday-of-every-november) produces the wrong results:
- Occurrence: 11/23/2000 12:00:00 AM -- Thursday
- Occurrence: 11/23/2001 12:00:00 AM -- Friday
- Occurrence: 11/23/2002 12:00:00 AM -- Saturday
- Occurrence: 11/23/2003 12:00:00 AM -- Sunday
- Occurrence: 11/23/2004 12:00:00 AM -- Tuesday
- Occurrence: 11/23/2005 12:00:00 AM -- Wednesday
- Occurrence: 11/23/2006 12:00:00 AM -- Thursday
- Occurrence: 11/23/2007 12:00:00 AM -- Friday
- Occurrence: 11/23/2008 12:00:00 AM -- Sunday
- Occurrence: 11/23/2009 12:00:00 AM -- Monday
- Occurrence: 11/23/2010 12:00:00 AM -- Tuesday
- Occurrence: 11/23/2011 12:00:00 AM -- Wednesday
- Occurrence: 11/23/2012 12:00:00 AM -- Friday
- Occurrence: 11/23/2013 12:00:00 AM -- Saturday
- Occurrence: 11/23/2014 12:00:00 AM -- Sunday
- Occurrence: 11/23/2015 12:00:00 AM -- Monday
- Occurrence: 11/23/2016 12:00:00 AM -- Wednesday

I am trying (and failing) to figure out how to build a recurrence rule for Thanksgiving...  Could you update the example?

Thanks!

**Comment by erpeters** [comment]
Might this be the answer?

``` csharp
var e = new Event
{
    DtStart = new CalDateTime(DateTime.Parse("2000-11-23T00:00:00")),
    DtEnd = new CalDateTime(DateTime.Parse("2000-11-23T23:59:59")),
    RecurrenceRules =  new List<IRecurrencePattern>
    {
        new RecurrencePattern
        {
            Frequency = FrequencyType.Yearly,
            Interval = 1,
            ByMonth = new List<int> { 11 },
            ByDay = new List<IWeekDay> { new Ical.Net.DataTypes.WeekDay { DayOfWeek = DayOfWeek.Thursday, Offset = 4} },
            Until = DateTime.MaxValue
        }
    }
};
```

**Comment by rianjs** [comment]
Yikes, my example recurrence rule makes no sense at all. It's so bad it's funny.

Thanks for the catch; I'll fix the docs, and close this issue when I do.

**Comment by rianjs** [comment]
Your fix was spot on. I've updated the page.

**Comment by rianjs** [comment]
Updated the unit test to assert the right things.

61e95887b620f46d8a3dc637f2474bc3df571ae5
