### ISSUE TITLE
Add support for jCal (RFC-7529) a JSON format for iCalendar data

### ISSUE THREAD

**Issue by Terebi42** [ical-org/ical.net#96]
https://tools.ietf.org/html/rfc7529

https://stackoverflow.com/questions/35757778/rrule-for-repeating-monthly-on-the-31st-or-closest-day

**Comment by rianjs** [comment]
I'm going to close this as a dupe/subset of #84

**Comment by rianjs** [comment]
Actually your issues were different, re-opening and re-titling.
